-- T14: Add MySQL columns for Abacws outdoor weather feed UUIDs (bldg1)
-- Generated by implementation plan T14 — do not edit by hand.
-- UUIDs are deterministic: MD5("bldg1:<feed_id>")
-- Run: docker exec -i abacws-mysql mysql -u root -p<password> sensordb < add_weather_feed_columns.sql

ALTER TABLE sensor_data
  ADD COLUMN IF NOT EXISTS `89d4f4fe-8964-0587-a47c-46e18340908a` DECIMAL(6,2) NULL
    COMMENT 'outside_weather_temp';

ALTER TABLE sensor_data
  ADD COLUMN IF NOT EXISTS `68026b21-faa3-d860-d7d8-8a76b55ba790` DECIMAL(6,2) NULL
    COMMENT 'outside_weather_humidity';

ALTER TABLE sensor_data
  ADD COLUMN IF NOT EXISTS `fc0e05a6-5606-36ab-d512-817cf3fdbe9f` DECIMAL(6,2) NULL
    COMMENT 'outside_weather_wind';
