# -*- coding: utf-8 -*-
"""Synthetic data must never read as real (V6-T62 conformance).

Everything in this repo that GENERATES sensor points must declare them as generated. The rule
is not decorative: a building that mixes a real estate with provisioned coverage answers from
both, and an answer that cannot tell them apart is a claim about the physical world backed by a
random number generator.

**This test exists because the check failed on its own author.** The V6-T26 plant provisioner
wrote 74 points with `ref:hasTimeseriesId` and no `ontosage:isSimulated`, while every other
synthetic sensor in the same building declared it. Nothing caught it — the registry marked the
STORE synthetic, which looks like the same guarantee and is not: an answer cites the point, not
the table.

Scoped to **generated** files on purpose. Real sensors legitimately carry no `isSimulated`, and
a rule demanding it everywhere would either be switched off or would train people to declare
real hardware as simulated — both worse than no rule.

Runs in the PARKED state (the committed tree has no active building), so it resolves the
building directory wherever it currently is.
"""

import re
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

REPO = Path(__file__).resolve().parent.parent

#: The marker every generator in this repo writes into its output header.
GENERATED_MARKER = "GENERATED by scripts/"

#: A subject carrying this is READABLE — it resolves to rows somebody can be shown.
TIMESERIES_MARKER = "ref:hasTimeseriesId"

DECLARATION = "ontosage:isSimulated"


def _building_dirs():
    """Every building's input directory, active (`input/`) or parked (`bldgN/`).

    A test that only looked in `input/` would pass vacuously in the committed state — which is
    the state CI and a fresh clone see, and therefore the only state where it matters.
    """
    dirs = [REPO / "input"] if (REPO / "input").is_dir() else []
    dirs += sorted(p for p in REPO.glob("bldg*") if p.is_dir())
    return dirs


def _generated_ttls():
    out = []
    for d in _building_dirs():
        for ttl in sorted(d.glob("*.ttl")):
            try:
                head = ttl.read_text(encoding="utf-8", errors="ignore")[:2000]
            except OSError:
                continue
            if GENERATED_MARKER in head:
                out.append(ttl)
    return out


def _subject_blocks(text: str):
    """(subject, block) for each `subject ... .` statement group in a Turtle file.

    Deliberately simple: these are generator outputs with a fixed shape, and a full parser here
    would test rdflib rather than the generators.
    """
    blocks = []
    current_subject = None
    buf = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith("@prefix"):
            continue
        if re.match(r"^\S+\s", line) and not line.startswith((" ", "\t")) and stripped:
            if current_subject:
                blocks.append((current_subject, "\n".join(buf)))
            current_subject = stripped.split()[0]
            buf = [stripped]
        elif current_subject:
            buf.append(stripped)
    if current_subject:
        blocks.append((current_subject, "\n".join(buf)))
    return blocks


def test_at_least_one_generated_ttl_is_present():
    """POSITIVE CONTROL. Without it, a rename of the generator marker would make every
    assertion below pass by iterating over nothing — the failure mode where a green suite is
    testing an empty set."""
    found = _generated_ttls()
    assert found, (
        "no generated TTL found in any building directory; either the generators stopped "
        f"writing the {GENERATED_MARKER!r} header or this test is looking in the wrong place"
    )


def test_every_generated_readable_point_declares_itself_simulated():
    """The rule V6-T26's own output broke."""
    offenders = []
    for ttl in _generated_ttls():
        text = ttl.read_text(encoding="utf-8", errors="ignore")
        for subject, block in _subject_blocks(text):
            if TIMESERIES_MARKER in block and DECLARATION not in block:
                offenders.append(f"{ttl.name}:{subject}")
    assert not offenders, (
        "generated points carry a timeseries reference but do not declare "
        f"{DECLARATION}, so an answer citing them cannot say the reading is synthetic: "
        f"{offenders[:8]}{' ...' if len(offenders) > 8 else ''}"
    )


def test_the_declaration_is_a_boolean_not_a_string():
    """`"true"` as a plain STRING sorts and filters differently from a boolean, so a SPARQL
    filter on the declaration would silently miss it.

    Turtle spells a boolean two equally valid ways -- bare `true` and `"true"^^xsd:boolean` --
    and this codebase uses both. Demanding one spelling would fail on correct files, which is
    how a conformance rule gets switched off. The thing that is actually wrong is a QUOTED
    string with no datatype.
    """
    bad = []
    for ttl in _generated_ttls():
        for line in ttl.read_text(encoding="utf-8", errors="ignore").splitlines():
            # A COMMENT describing the rule is not a violation of it. Several generators
            # explain the convention in their header, and scanning those as data made the
            # files that document the rule best look like the ones breaking it.
            if DECLARATION not in line or line.lstrip().startswith("#"):
                continue
            value = line.split(DECLARATION, 1)[1].strip().rstrip(";.").strip()
            if value in ("true", "false"):
                continue
            if "xsd:boolean" in value:
                continue
            bad.append(f"{ttl.name}: {line.strip()}")
    assert not bad, f"isSimulated declared as an untyped string: {bad[:5]}"


def test_a_generator_that_writes_readings_declares_them_in_its_source():
    """Fails CLOSED for a FUTURE generator.

    The tests above check OUTPUT, which only exists once somebody runs the script. This checks
    the script, so a new provisioner that forgets the declaration fails before it has ever been
    run -- the only point at which the omission is cheap to fix.

    EMITTING a reading is distinguished from QUERYING for one: a script that writes points
    emits `ref:hasTimeseriesId "<literal>"`, while one that merely looks them up binds a
    variable (`?uuid`). Treating the two alike flagged the meter-topology and
    configuration-history provisioners, neither of which creates a sensor.
    """
    offenders = []
    for script in sorted((REPO / "scripts").glob("provision_*.py")):
        src = script.read_text(encoding="utf-8", errors="ignore")
        # A generator WRITING a point emits the predicate followed by a quoted literal;
        # one merely LOOKING points up binds a SPARQL variable (`?uuid`) instead.
        emits_readings = 'hasTimeseriesId "' in src
        if emits_readings and DECLARATION not in src:
            offenders.append(script.name)
    assert (
        not offenders
    ), f"these provisioners emit readable points without declaring them simulated: {offenders}"


def test_registries_declare_the_nature_of_every_ACTIVE_store():
    """The store-level half of the same guarantee.

    Scoped to the stores `building.yaml` actually activates. The registry also ships ready-made
    template blocks for a dozen backends nobody here uses (mariadb, aurora-mysql, ...); a rule
    that demanded provenance from an unused template would be noise, and noise gets muted.

    NOT a substitute for the point-level declaration -- an answer cites the point, not the
    table -- which is precisely the reasoning that let the plant points ship undeclared.
    """
    import yaml

    missing = []
    for d in _building_dirs():
        registry = d / "database_registry.yaml"
        building = d / "building.yaml"
        if not registry.is_file() or not building.is_file():
            continue
        active = set(
            ((yaml.safe_load(building.read_text(encoding="utf-8")) or {}).get("storage") or {}).get(
                "databases"
            )
            or []
        )
        if not active:
            continue
        dbs = (yaml.safe_load(registry.read_text(encoding="utf-8")) or {}).get("databases") or {}
        for key in sorted(active):
            spec = dbs.get(key)
            if isinstance(spec, dict) and not spec.get("nature"):
                missing.append(f"{d.name}/{key}")
    assert not missing, f"ACTIVE datasources with no declared nature: {missing[:8]}"
