# -*- coding: utf-8 -*-
"""The narration validators, replayed over every stored answer, lose no fact from a good one.

A hygiene pass earns its place only if it is safe on the answers that were already right. This
replays the ~1,150 answers stored under ``docs/phase0/`` (each paired with its hand label) through
``validate_narration`` with the lane the run recorded, and asserts on the ones a reader labelled
``GOOD_ANSWER`` / ``GOOD_DECLINE``:

* every number that disappears with a removed sentence is in a hand-reviewed allowlist, and each
  allowlisted number is a list marker, an invented alert threshold or an uncited norm -- never an
  observed figure;
* footers and table rows survive byte for byte, and no answer is emptied;
* the defects the tracker names (BUG-832, CAVEAT-833) are actually removed from the answers that
  carried them.

A NEW removal in a good answer fails this test until a person reads it and adds it below. The diff
table is regenerated by ``python scripts/replay_narration_validators.py``.
"""

import importlib.util
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "scripts" / "replay_narration_validators.py"
GOOD = {"GOOD_ANSWER", "GOOD_DECLINE"}

if not (REPO / "docs" / "phase0" / "fresh_tail_run1.jsonl").exists():  # pragma: no cover
    pytest.skip("docs/phase0 answer files are not present", allow_module_level=True)


def _load():
    spec = importlib.util.spec_from_file_location("replay_narration_validators", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["replay_narration_validators"] = mod
    spec.loader.exec_module(mod)
    return mod


replay_mod = _load()
NV = replay_mod.load_validators()

#: Hand-reviewed: numbers that vanish from a GOOD answer with the sentence that carried them.
#: Each is a list marker ("1.", "2."), an alert threshold the model invented (1,000 / 1,100 /
#: 24.0), or the number of a norm the model asserted (a delta-T "of 8-9 C" being "typical").
REVIEWED_ORPHANS = {
    ("phase0_run5.md", 120): {"9"},
    ("phase0_run6.md", 120): {"10", "12"},
    ("demo_rehearsal_2026-09-18_run1", 19): {"1", "1,000", "2", "3"},
    ("demo_rehearsal_2026-09-18_run1", 32): {"8", "9"},
    ("demo_rehearsal_2026-09-18_run2", 19): {"1", "1,100", "2", "3"},
    ("demo_rehearsal_2026-09-18_run2", 32): {"10", "12"},
    ("demo_rehearsal_2026-09-18_run2", 36): {"24.0"},
    # 10-20 % "typical" lighting savings, and 0.18-0.36 kWh, which is 3.64 kWh x the invented 5-10 %
    ("demo_rehearsal_2026-09-18_run3_combined", 13): {"10", "20", "0.18", "0.36"},
    ("demo_rehearsal_2026-09-18_run3_combined", 19): {"1", "2", "3"},
}


@pytest.fixture(scope="module")
def changed():
    return replay_mod.replay()


@pytest.fixture(scope="module")
def answers():
    return list(replay_mod.iter_answers())


def test_the_replay_covers_every_stored_answer(answers):
    assert len(answers) >= 1100
    assert {a["verdict"] for a in answers} >= {"GOOD_ANSWER", "GOOD_DECLINE", "WEIRD"}


def test_no_observed_figure_leaves_an_answer_a_reader_labelled_good(changed):
    unreviewed = []
    for r in changed:
        if r["verdict"] not in GOOD:
            continue
        allowed = REVIEWED_ORPHANS.get((r["file"], r["row"]), set())
        extra = set(r["orphaned_numbers"]) - allowed
        if extra:
            unreviewed.append((r["file"], r["row"], sorted(extra), r["changes"]))
    assert not unreviewed, (
        "a removal in a GOOD answer carries numbers nobody has reviewed; read it and either fix the "
        f"validator or add it to REVIEWED_ORPHANS: {unreviewed}"
    )


def test_every_removal_in_a_good_answer_is_a_named_kind_of_edit(changed):
    kinds = {
        "drop_unasked_advice",
        "strip_uncited_norms",
        "check_counts_against_lists",
        "no_range_as_delta",
        "fix_advice_direction",
        "fix_total_called_daily_average",
        "state_method_of_computed_total",
    }
    for r in changed:
        for c in r["changes"]:
            assert c["validator"] in kinds, c


def test_the_validators_touch_a_small_minority_of_answers(changed, answers):
    # a runaway pattern shows up here first
    assert len(changed) <= 0.08 * len(answers), (len(changed), len(answers))


def test_footers_and_table_rows_survive_byte_for_byte_and_nothing_is_emptied(answers):
    for a in answers:
        out = NV.validate_narration(a["question"], a["answer"], a["lane"]).text
        assert out.strip(), (a["file"], a["row"])
        before = a["answer"].split("\n")
        after = set(out.split("\n"))
        for line in before:
            s = line.lstrip()
            if s.startswith("|") or s.startswith(("**You might also ask", "*Sources:")):
                assert line in after, (a["file"], a["row"], line[:80])


def test_the_pass_is_idempotent_over_the_whole_corpus(answers):
    for a in answers:
        once = NV.validate_narration(a["question"], a["answer"], a["lane"]).text
        twice = NV.validate_narration(a["question"], once, a["lane"]).text
        assert twice == once, (a["file"], a["row"])


def _plain(s):
    """The stored answers use narrow no-break spaces between a number and its unit."""
    return s.replace(" ", " ").replace(" ", " ")


def _text(answers, file, row, lane=None):
    a = next(x for x in answers if x["file"] == file and x["row"] == row)
    after = NV.validate_narration(a["question"], a["answer"], lane or a["lane"]).text
    return _plain(a["answer"]), _plain(after)


@pytest.mark.parametrize("row", [12, 26, 27, 28, 36, 37, 38])
def test_the_scripted_answers_that_carried_a_recommendation_no_longer_do(answers, row):
    for run in ("demo_rehearsal_2026-09-18_run1", "demo_rehearsal_2026-09-18_run2"):
        before, after = _text(answers, run, row)
        if "ecommendation" in before:
            assert "ecommendation" not in after, (run, row)


def test_bug_832_scripted_examples_are_gone(answers):
    _, after = _text(answers, "demo_rehearsal_2026-09-18_run2", 26)
    assert "audit of the HVAC airflow" not in after  # 0.2 C spread
    _, after = _text(answers, "demo_rehearsal_2026-09-18_run2", 19)
    assert "1,100" not in after and "Recommendations" not in after  # alert at the observed maximum
    _, after = _text(answers, "demo_rehearsal_2026-09-18_run2", 38)
    assert "calibration check" not in after
    _, after = _text(answers, "demo_rehearsal_2026-09-18_run2", 32)
    assert "is typical" not in after and "expected healthy range" not in after
    assert "10.5–11.1 °C" in after, "the reading beside the removed norm stays"
    _, after = _text(answers, "demo_rehearsal_2026-09-18_run2", 36)
    assert "24.0" not in after


def test_caveat_833_examples_are_gone(answers):
    _, after = _text(answers, "demo_rehearsal_2026-09-18_run3_combined", 27)
    assert "moves toward the 800" not in after
    before, after = _text(answers, "demo_rehearsal_2026-09-18_run3_combined", 32)
    assert "minus minimum entering" in before and "minus minimum entering" not in after
    before, after = _text(answers, "fresh_tail_B_run1", 8)
    assert "14 people per floor" in before and "14 people per floor" not in after
    assert "Floor 3: 10 people" in after, "the counts themselves stay"
    before, after = _text(answers, "demo_rehearsal_2026-09-18_run2", 9)
    assert "Floors 2 and 5 and the parking ventilation" in before
    assert "Floors 2 and 5 and the parking ventilation" not in after
    assert "2 do not have an exception" in after
