"""
db_ontology.py — register the SENSOR METADATA of an external database connection
into GraphDB so it becomes queryable.

Connecting a database (credentials) is only half of a data source: the pipeline
answers a question by resolving, via SPARQL, a sensor + its UUID + which DB it is
``ref:storedAt``, then routing the SQL fetch to that DB. Without Brick triples
pointing at the connection, nothing in the ontology references it and it is never
reached. This module adds that missing half.

Two ways to supply the metadata (both land in one named graph
``urn:ontosage:db:<key>`` — PUT replaces atomically, so re-registering is idempotent):

  * ``register_ttl`` — the admin uploads a Brick TTL (real sensors + real UUIDs +
    ``ref:storedAt bldg:<key>``). Validated as Turtle before upload.
  * ``register_points`` — the admin lists points (local / brick_class / location /
    unit / **uuid**); we generate the canonical Brick TTL (dual
    ``ashrae:``/``ref:hasExternalReference`` → ``ref:TimeseriesReference``) with
    ``ref:storedAt bldg:<key>``.

UUIDs here are the REAL ids that exist in the external DB (not derived) — the data
already lives there, so the metadata must match it.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from shared.utils import get_logger

logger = get_logger(__name__)

try:
    import httpx as _httpx
except ImportError:  # pragma: no cover
    _httpx = None  # type: ignore[assignment]

_POINT_REQUIRED = ("local", "brick_class", "location", "uuid")


def _safe_db_key(db_key: str) -> str:
    """Filesystem/URI-safe form of a connection key (alnum / '_' / '-')."""
    return "".join(c if (c.isalnum() or c in "_-") else "_" for c in db_key)


def graph_uri_for_db(db_key: str) -> str:
    """LEGACY named graph a DB's sensors used to live in (pre file-persistence).

    Retained only so the migration path (:func:`clear_graph`, the backfill script) can find and
    clean up graphs created before sensors were persisted to ``input/``. New registrations write
    a file graph instead — see :func:`sensors_filename` / :func:`graph_uri_for_db_file`.
    """
    return f"urn:ontosage:db:{_safe_db_key(db_key)}"


def sensors_filename(db_key: str) -> str:
    """``input/`` filename backing a DB's sensor metadata (the source of truth).

    The file sits directly under ``input/`` so ``ttl_uploader`` reloads it on every restart
    (flat-layout, non-schema discovery) — no per-file wiring. The name deliberately avoids the
    shared-schema tokens (brick/rec/s223/schema) so it is treated as building data, not schema.
    """
    return f"db_{_safe_db_key(db_key)}_sensors.ttl"


def graph_uri_for_db_file(db_key: str) -> str:
    """Named graph the sensors file syncs into — identical to ttl_uploader's file-graph URI."""
    from orchestrator.services.input_ttl_store import graph_uri_for_filename

    return graph_uri_for_filename(sensors_filename(db_key))


def _resolve_settings(graphdb_url, repository, building_namespace):
    from shared.config import settings

    return (
        graphdb_url or settings.GRAPHDB_URL,
        repository or settings.GRAPHDB_REPOSITORY,
        building_namespace or settings.BUILDING_NAMESPACE,
    )


def build_points_ttl(building_namespace: str, db_key: str, points: List[Dict[str, Any]]) -> str:
    """Build a Brick TTL registering `points` as UUID-keyed timeseries points on db_key.

    Delegates to the single canonical builder (brick_ttl) so external-DB sensors get
    the exact same syntax as the hand-authored bldg1 ontology (shared external-ref
    node, rdf:type, brick:Class/Entity, ref:storedAt bldg:<db_key>).
    """
    from orchestrator.services.brick_ttl import points_document

    pts = [{**pt, "stored_at": db_key} for pt in points]
    return points_document(
        building_namespace,
        pts,
        header=f"External DB '{db_key}' sensor metadata — generated by db_ontology. Do not edit.",
    )


def validate_points(points: List[Dict[str, Any]]) -> List[str]:
    """Return a list of problems (empty = valid)."""
    issues: List[str] = []
    seen = set()
    for i, pt in enumerate(points or []):
        if not isinstance(pt, dict):
            issues.append(f"point[{i}]: must be an object")
            continue
        for key in _POINT_REQUIRED:
            if not pt.get(key):
                issues.append(f"point[{i}]: missing '{key}'")
        local = pt.get("local")
        if local in seen:
            issues.append(f"point[{i}]: duplicate local '{local}'")
        seen.add(local)
    return issues


def validate_ttl(ttl_text: str, db_key: str) -> List[str]:
    """Parse the uploaded Turtle and sanity-check it references this DB. Warnings only
    for the storedAt check; a parse error is a hard issue."""
    issues: List[str] = []
    try:
        import rdflib

        g = rdflib.Graph()
        g.parse(data=ttl_text, format="turtle")
        if len(g) == 0:
            issues.append("TTL parsed but contains no triples")
    except Exception as e:
        return [f"TTL parse error: {e}"]
    if f":{db_key}" not in ttl_text and db_key not in ttl_text:
        issues.append(
            f"warning: TTL does not mention '{db_key}' — sensors must use "
            f"ref:storedAt bldg:{db_key} to route to this connection"
        )
    return issues


# ── GraphDB I/O ────────────────────────────────────────────────────────────────


async def graph_triple_count(
    db_key: str,
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> int:
    """Count triples currently registered for a DB's sensor graph (0 if none/unreachable).

    Reads the file graph (``urn:ontosage:ttl:db_<key>_sensors.ttl``) the sensors are now
    persisted into — the same graph both the live sync and the restart uploader target.
    """
    if _httpx is None:
        return 0
    url, repo, _ = _resolve_settings(graphdb_url, repository, None)
    graph = graph_uri_for_db_file(db_key)
    q = f"SELECT (COUNT(*) AS ?n) WHERE {{ GRAPH <{graph}> {{ ?s ?p ?o }} }}"
    endpoint = f"{url.rstrip('/')}/repositories/{repo}"
    owns = client is None
    client = client or _httpx.AsyncClient(timeout=30.0)
    try:
        resp = await client.post(
            endpoint,
            content=q.encode("utf-8"),
            headers={
                "Content-Type": "application/sparql-query",
                "Accept": "application/sparql-results+json",
            },
        )
        if resp.status_code == 200:
            b = resp.json()["results"]["bindings"]
            return int(b[0]["n"]["value"]) if b else 0
        return 0
    except Exception:  # pragma: no cover - network
        return 0
    finally:
        if owns:
            await client.aclose()


async def graph_triple_counts(
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> Dict[str, int]:
    """Batch: triple count per DB sensor graph in ONE grouped query → {db_key: count}.

    Lets the admin console show every connection's sensor count with a single request
    instead of one probe per card (which floods the rate limiter at scale).
    """
    if _httpx is None:
        return {}
    url, repo, _ = _resolve_settings(graphdb_url, repository, None)
    # DB sensor files land in urn:ontosage:ttl:db_<key>_sensors.ttl — grab every such file graph.
    prefix = "urn:ontosage:ttl:db_"
    suffix = "_sensors.ttl"
    q = (
        "SELECT ?g (COUNT(*) AS ?n) WHERE { GRAPH ?g { ?s ?p ?o } "
        f'FILTER(STRSTARTS(STR(?g), "{prefix}") && STRENDS(STR(?g), "{suffix}")) }} GROUP BY ?g'
    )
    endpoint = f"{url.rstrip('/')}/repositories/{repo}"
    owns = client is None
    client = client or _httpx.AsyncClient(timeout=30.0)
    try:
        resp = await client.post(
            endpoint,
            content=q.encode("utf-8"),
            headers={
                "Content-Type": "application/sparql-query",
                "Accept": "application/sparql-results+json",
            },
        )
        if resp.status_code != 200:
            return {}
        out: Dict[str, int] = {}
        for b in resp.json()["results"]["bindings"]:
            g = b["g"]["value"]
            if g.startswith(prefix) and g.endswith(suffix):
                key = g[len(prefix) : -len(suffix)]
            else:
                key = g
            out[key] = int(b["n"]["value"])
        return out
    except Exception:  # pragma: no cover - network
        return {}
    finally:
        if owns:
            await client.aclose()


# ── Public registration API ─────────────────────────────────────────────────


async def register_points(
    db_key: str,
    points: List[Dict[str, Any]],
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    building_namespace: Optional[str] = None,
    client: Optional[Any] = None,
) -> Dict[str, Any]:
    """Generate Brick triples for `points` and MERGE them into the DB's ``input/`` sensor file.

    The file (source of truth) is written atomically + backed up, then its named graph is synced
    to GraphDB, so the sensors survive a GraphDB volume reset and reload on restart. Uses an UPSERT
    merge (``replace_subjects=True``): registering ADDS new sensors and keeps previously-registered
    ones, but re-submitting an existing sensor REPLACES its triples (same uuid, no duplicate
    external-ref nodes) rather than piling stale copies on top.
    """
    issues = validate_points(points)
    if issues:
        return {"ok": False, "error": "; ".join(issues)}
    _url, _repo, ns = _resolve_settings(graphdb_url, repository, building_namespace)
    ttl = build_points_ttl(ns, db_key, points)

    from orchestrator.services.input_ttl_store import persist_ttl_file

    res = await persist_ttl_file(
        sensors_filename(db_key), ttl, merge=True, replace_subjects=True, client=client
    )
    ok = bool(res.get("ok"))
    return {
        "ok": ok,
        "db_key": db_key,
        "graph": res.get("graph", graph_uri_for_db_file(db_key)),
        "file": res.get("file"),
        "points": len(points),
        "persisted": True,
        "error": None if ok else "persist/graph-sync failed",
    }


async def clear_graph(
    db_key: str,
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> bool:
    """Remove a connection's sensors so the removal PERSISTS across restarts.

    Moves the ``input/db_<key>_sensors.ttl`` file to ``input/.trash/`` and drops its file graph —
    a graph-only delete would silently reappear when ``ttl_uploader`` reloads the file on the next
    boot. Also drops the LEGACY ``urn:ontosage:db:<key>`` graph so connections registered before
    the file-persistence migration are cleaned up too.
    """
    from orchestrator.services.input_ttl_store import trash_ttl_file
    from orchestrator.services.ontology_manager import drop_named_graph

    res = await trash_ttl_file(sensors_filename(db_key), client=client)
    # Best-effort cleanup of the pre-migration graph; ignore its result for the return value.
    await drop_named_graph(graph_uri_for_db(db_key), client=client)
    return bool(res.get("ok"))


async def register_ttl(
    db_key: str,
    ttl_text: str,
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> Dict[str, Any]:
    """Validate + MERGE an admin-provided Brick TTL into the DB's ``input/`` sensor file.

    Same durability + upsert semantics as :func:`register_points`: the file is the source of truth,
    its graph is synced to GraphDB, and re-submitting a sensor replaces it (``replace_subjects``)
    while other registered sensors are preserved.
    """
    issues = validate_ttl(ttl_text, db_key)
    hard = [i for i in issues if not i.startswith("warning:")]
    if hard:
        return {"ok": False, "error": "; ".join(hard)}

    from orchestrator.services.input_ttl_store import persist_ttl_file

    res = await persist_ttl_file(
        sensors_filename(db_key), ttl_text, merge=True, replace_subjects=True, client=client
    )
    ok = bool(res.get("ok"))
    return {
        "ok": ok,
        "db_key": db_key,
        "graph": res.get("graph", graph_uri_for_db_file(db_key)),
        "file": res.get("file"),
        "warnings": [i for i in issues if i.startswith("warning:")],
        "persisted": True,
        "error": None if ok else "persist/graph-sync failed",
    }
