"""
db_ontology.py — register the SENSOR METADATA of an external database connection
into GraphDB so it becomes queryable.

Connecting a database (credentials) is only half of a data source: the pipeline
answers a question by resolving, via SPARQL, a sensor + its UUID + which DB it is
``ref:storedAt``, then routing the SQL fetch to that DB. Without Brick triples
pointing at the connection, nothing in the ontology references it and it is never
reached. This module adds that missing half.

Two ways to supply the metadata (both land in one named graph
``urn:ontosage:db:<key>`` — PUT replaces atomically, so re-registering is idempotent):

  * ``register_ttl`` — the admin uploads a Brick TTL (real sensors + real UUIDs +
    ``ref:storedAt bldg:<key>``). Validated as Turtle before upload.
  * ``register_points`` — the admin lists points (local / brick_class / location /
    unit / **uuid**); we generate the canonical Brick TTL (dual
    ``ashrae:``/``ref:hasExternalReference`` → ``ref:TimeseriesReference``) with
    ``ref:storedAt bldg:<key>``.

UUIDs here are the REAL ids that exist in the external DB (not derived) — the data
already lives there, so the metadata must match it.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from urllib.parse import quote as _url_quote

from shared.utils import get_logger

logger = get_logger(__name__)

try:
    import httpx as _httpx
except ImportError:  # pragma: no cover
    _httpx = None  # type: ignore[assignment]

_POINT_REQUIRED = ("local", "brick_class", "location", "uuid")


def graph_uri_for_db(db_key: str) -> str:
    """Named graph holding an external DB's sensor metadata."""
    safe = "".join(c if (c.isalnum() or c in "_-") else "_" for c in db_key)
    return f"urn:ontosage:db:{safe}"


def _resolve_settings(graphdb_url, repository, building_namespace):
    from shared.config import settings

    return (
        graphdb_url or settings.GRAPHDB_URL,
        repository or settings.GRAPHDB_REPOSITORY,
        building_namespace or settings.BUILDING_NAMESPACE,
    )


def build_points_ttl(building_namespace: str, db_key: str, points: List[Dict[str, Any]]) -> str:
    """Build a Brick TTL registering `points` as UUID-keyed timeseries points on db_key.

    Delegates to the single canonical builder (brick_ttl) so external-DB sensors get
    the exact same syntax as the hand-authored bldg1 ontology (shared external-ref
    node, rdf:type, brick:Class/Entity, ref:storedAt bldg:<db_key>).
    """
    from orchestrator.services.brick_ttl import points_document

    pts = [{**pt, "stored_at": db_key} for pt in points]
    return points_document(
        building_namespace,
        pts,
        header=f"External DB '{db_key}' sensor metadata — generated by db_ontology. Do not edit.",
    )


def validate_points(points: List[Dict[str, Any]]) -> List[str]:
    """Return a list of problems (empty = valid)."""
    issues: List[str] = []
    seen = set()
    for i, pt in enumerate(points or []):
        if not isinstance(pt, dict):
            issues.append(f"point[{i}]: must be an object")
            continue
        for key in _POINT_REQUIRED:
            if not pt.get(key):
                issues.append(f"point[{i}]: missing '{key}'")
        local = pt.get("local")
        if local in seen:
            issues.append(f"point[{i}]: duplicate local '{local}'")
        seen.add(local)
    return issues


def validate_ttl(ttl_text: str, db_key: str) -> List[str]:
    """Parse the uploaded Turtle and sanity-check it references this DB. Warnings only
    for the storedAt check; a parse error is a hard issue."""
    issues: List[str] = []
    try:
        import rdflib

        g = rdflib.Graph()
        g.parse(data=ttl_text, format="turtle")
        if len(g) == 0:
            issues.append("TTL parsed but contains no triples")
    except Exception as e:
        return [f"TTL parse error: {e}"]
    if f":{db_key}" not in ttl_text and db_key not in ttl_text:
        issues.append(
            f"warning: TTL does not mention '{db_key}' — sensors must use "
            f"ref:storedAt bldg:{db_key} to route to this connection"
        )
    return issues


# ── GraphDB I/O ────────────────────────────────────────────────────────────────


async def _put_named_graph(
    graph_uri: str, ttl: str, graphdb_url: str, repository: str, client: Optional[Any] = None
) -> bool:
    if _httpx is None:
        logger.warning("[db_ontology] httpx not installed — cannot reach GraphDB")
        return False
    base = (graphdb_url or "").rstrip("/")
    endpoint = f"{base}/repositories/{repository}/rdf-graphs/service?graph={_url_quote(graph_uri, safe='')}"
    owns = client is None
    client = client or _httpx.AsyncClient(timeout=60.0)
    try:
        resp = await client.put(
            endpoint, content=ttl.encode("utf-8"), headers={"Content-Type": "text/turtle"}
        )
        if resp.status_code in (200, 204):
            return True
        logger.warning(
            f"[db_ontology] PUT <{graph_uri}> HTTP {resp.status_code}: {resp.text[:200]}"
        )
        return False
    except Exception as e:  # pragma: no cover - network
        logger.warning(f"[db_ontology] PUT <{graph_uri}> error: {e}")
        return False
    finally:
        if owns:
            await client.aclose()


async def graph_triple_count(
    db_key: str,
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> int:
    """Count triples currently registered for a DB's sensor graph (0 if none/unreachable)."""
    if _httpx is None:
        return 0
    url, repo, _ = _resolve_settings(graphdb_url, repository, None)
    graph = graph_uri_for_db(db_key)
    q = f"SELECT (COUNT(*) AS ?n) WHERE {{ GRAPH <{graph}> {{ ?s ?p ?o }} }}"
    endpoint = f"{url.rstrip('/')}/repositories/{repo}"
    owns = client is None
    client = client or _httpx.AsyncClient(timeout=30.0)
    try:
        resp = await client.post(
            endpoint,
            content=q.encode("utf-8"),
            headers={
                "Content-Type": "application/sparql-query",
                "Accept": "application/sparql-results+json",
            },
        )
        if resp.status_code == 200:
            b = resp.json()["results"]["bindings"]
            return int(b[0]["n"]["value"]) if b else 0
        return 0
    except Exception:  # pragma: no cover - network
        return 0
    finally:
        if owns:
            await client.aclose()


async def graph_triple_counts(
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> Dict[str, int]:
    """Batch: triple count per DB sensor graph in ONE grouped query → {db_key: count}.

    Lets the admin console show every connection's sensor count with a single request
    instead of one probe per card (which floods the rate limiter at scale).
    """
    if _httpx is None:
        return {}
    url, repo, _ = _resolve_settings(graphdb_url, repository, None)
    prefix = "urn:ontosage:db:"
    q = (
        "SELECT ?g (COUNT(*) AS ?n) WHERE { GRAPH ?g { ?s ?p ?o } "
        f'FILTER(STRSTARTS(STR(?g), "{prefix}")) }} GROUP BY ?g'
    )
    endpoint = f"{url.rstrip('/')}/repositories/{repo}"
    owns = client is None
    client = client or _httpx.AsyncClient(timeout=30.0)
    try:
        resp = await client.post(
            endpoint,
            content=q.encode("utf-8"),
            headers={
                "Content-Type": "application/sparql-query",
                "Accept": "application/sparql-results+json",
            },
        )
        if resp.status_code != 200:
            return {}
        out: Dict[str, int] = {}
        for b in resp.json()["results"]["bindings"]:
            g = b["g"]["value"]
            key = g[len(prefix) :] if g.startswith(prefix) else g
            out[key] = int(b["n"]["value"])
        return out
    except Exception:  # pragma: no cover - network
        return {}
    finally:
        if owns:
            await client.aclose()


# ── Public registration API ─────────────────────────────────────────────────


async def register_points(
    db_key: str,
    points: List[Dict[str, Any]],
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    building_namespace: Optional[str] = None,
    client: Optional[Any] = None,
) -> Dict[str, Any]:
    """Generate + upload Brick triples for `points` into the DB's named graph."""
    issues = validate_points(points)
    if issues:
        return {"ok": False, "error": "; ".join(issues)}
    url, repo, ns = _resolve_settings(graphdb_url, repository, building_namespace)
    ttl = build_points_ttl(ns, db_key, points)
    graph = graph_uri_for_db(db_key)
    ok = await _put_named_graph(graph, ttl, url, repo, client=client)
    return {
        "ok": ok,
        "db_key": db_key,
        "graph": graph,
        "points": len(points),
        "error": None if ok else "GraphDB upload failed",
    }


async def clear_graph(
    db_key: str,
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> bool:
    """Delete the connection's sensor named graph (used when a connection is removed)."""
    if _httpx is None:
        return False
    url, repo, _ = _resolve_settings(graphdb_url, repository, None)
    graph = graph_uri_for_db(db_key)
    endpoint = (
        f"{url.rstrip('/')}/repositories/{repo}"
        f"/rdf-graphs/service?graph={_url_quote(graph, safe='')}"
    )
    owns = client is None
    client = client or _httpx.AsyncClient(timeout=30.0)
    try:
        resp = await client.delete(endpoint)
        return resp.status_code in (200, 204, 404)
    except Exception:  # pragma: no cover - network
        return False
    finally:
        if owns:
            await client.aclose()


async def register_ttl(
    db_key: str,
    ttl_text: str,
    *,
    graphdb_url: Optional[str] = None,
    repository: Optional[str] = None,
    client: Optional[Any] = None,
) -> Dict[str, Any]:
    """Validate + upload an admin-provided Brick TTL into the DB's named graph."""
    issues = validate_ttl(ttl_text, db_key)
    hard = [i for i in issues if not i.startswith("warning:")]
    if hard:
        return {"ok": False, "error": "; ".join(hard)}
    url, repo, _ = _resolve_settings(graphdb_url, repository, None)
    graph = graph_uri_for_db(db_key)
    ok = await _put_named_graph(graph, ttl_text, url, repo, client=client)
    return {
        "ok": ok,
        "db_key": db_key,
        "graph": graph,
        "warnings": [i for i in issues if i.startswith("warning:")],
        "error": None if ok else "GraphDB upload failed",
    }
