# -*- coding: utf-8 -*-
"""Where a reading came from — judged per OBSERVATION, not per table.

NAMED `observation_provenance` and not `provenance`: `services/provenance.py` already
exists and does a different job — it records which STORES a turn touched and renders the
source chips under an answer. The two are complementary, not rival: that one says which
stores were read, this one says whether a given reading from them is a measurement.
Naming this `provenance` overwrote it and broke twelve tests.

V12-04 part 2 of 3, review risk R4 and case B06.

WHY PER-TABLE WAS NEVER GOING TO WORK HERE
-------------------------------------------
The existing signal is `DataSourceRegistry.provenance_for_table(ts_table)`, a function of a
table NAME. The review says plainly (p. 11): *"Apply provenance rules per observation or
batch, not only per Point; stores or namespaces alone do not enforce them."*

bldg1 is the proof. Measured 2026-09-11:

    sensor_data   697,329 rows   2025-01-01 -> 2026-09-11
      <= 2025-03-09   576,557    the real snapshot the owner loaded
      >  2025-03-09   120,772    generated by data-publisher (PUBLISH_WIDE=true)

One table, both origins, by design and user-confirmed. No per-table flag can be right about
it. Worse, the real data stops eighteen months ago, so EVERY question about current
conditions reads generated rows — and `provenance_for_table("sensor_data")` returns None,
because provenance is read from `datasources.yaml`, which has zero entries for the wide
table while `database_registry.yaml` (a different file) is what routes to it.

THE TWO LEVELS, KEPT SEPARATE
-----------------------------
* **Point origin** — does a real instrument exist? `ontosage:isSimulated` on the point.
  1,408 points declare `true` (SATURATE-provisioned); 685 now declare `false` after
  V12-04 part 1; the rest inherit their store's declaration.
* **Observation origin** — was THIS reading measured or generated? The point's origin plus
  the store's declared `measured_through` boundary.

A SATURATE point has no real readings at all, so point-simulated settles it. A measured
point can still yield generated readings, which is what the boundary is for.

UNKNOWN IS A VERDICT, NOT A FAILURE
-----------------------------------
There is no default to "measured". Silence was precisely the defect: before part 1 nothing
in the graph positively asserted measurement, and 1,356 points said nothing while every
consumer read that as real. An undeclared origin returns UNKNOWN and the caller decides —
`admissible_for_operational_claim` treats UNKNOWN as inadmissible, because an operational
recommendation resting on evidence of unestablished origin is the thing R4 is about.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional


class Origin(str, Enum):
    """Where a reading came from. There is deliberately no fourth, hopeful value."""

    MEASURED = "measured"
    SIMULATED = "simulated"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class ProvenanceVerdict:
    origin: Origin
    #: What settled it, so a dossier can show the derivation rather than the conclusion.
    basis: str
    reason: str

    @property
    def admissible_for_operational_claim(self) -> bool:
        """Only a measurement supports a claim about how the building actually is.

        UNKNOWN is inadmissible. That is the whole point: before this, an undeclared
        origin was silently treated as measured, and a ranking could be won by a point
        nobody had ever established was real.
        """
        return self.origin is Origin.MEASURED


def _parse(ts: Any) -> Optional[datetime]:
    """A datetime from whatever the row carried, or None. Never raises."""
    if isinstance(ts, datetime):
        return ts
    if not ts:
        return None
    text = str(ts).strip().replace("Z", "+00:00")
    for fmt in (None, "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%d"):
        try:
            return datetime.fromisoformat(text) if fmt is None else datetime.strptime(text, fmt)
        except (ValueError, TypeError):
            continue
    return None


def _naive(dt: Optional[datetime]) -> Optional[datetime]:
    """Compare like with like. A boundary written without an offset must not raise
    against a row that carries one — that would turn a provenance question into a crash."""
    if dt is None:
        return None
    return dt.replace(tzinfo=None) if dt.tzinfo is not None else dt


def observation_origin(
    *,
    point_simulated: Optional[bool],
    store_synthetic: Optional[bool] = None,
    measured_through: Optional[Any] = None,
    observed_at: Optional[Any] = None,
) -> ProvenanceVerdict:
    """Judge one reading.

    Order matters and is not arbitrary:

    1. A point declared SIMULATED has no real readings, whatever the store or the date.
    2. A store declared synthetic produces nothing measured.
    3. A `measured_through` boundary judges the reading by its timestamp — the only rule
       that can be right about a table holding both origins.
    4. A point declared MEASURED, with no boundary to contradict it, yields measurements.
    5. Anything else is UNKNOWN. Not "probably fine".
    """
    if point_simulated is True:
        return ProvenanceVerdict(
            Origin.SIMULATED, "point",
            "the point declares ontosage:isSimulated true — no physical instrument exists",
        )
    if store_synthetic is True:
        return ProvenanceVerdict(
            Origin.SIMULATED, "store",
            "every reading in this store is declared synthetic",
        )

    if measured_through is not None:
        boundary = _naive(_parse(measured_through))
        seen = _naive(_parse(observed_at))
        if boundary is None:
            return ProvenanceVerdict(
                Origin.UNKNOWN, "boundary",
                f"the store declares measured_through={measured_through!r}, which is not a "
                "date this code can read, so no reading here can be judged",
            )
        if seen is None:
            return ProvenanceVerdict(
                Origin.UNKNOWN, "boundary",
                "this store holds measured and generated rows separated by a date, and "
                "this reading carries no usable timestamp, so which side it falls on is "
                "not established",
            )
        if seen <= boundary:
            return ProvenanceVerdict(
                Origin.MEASURED, "observation",
                f"recorded {seen.isoformat()}, at or before the store's measured_through "
                f"boundary of {boundary.isoformat()}",
            )
        return ProvenanceVerdict(
            Origin.SIMULATED, "observation",
            f"recorded {seen.isoformat()}, after the store's measured_through boundary of "
            f"{boundary.isoformat()} — this store's later rows are generated",
        )

    if point_simulated is False:
        return ProvenanceVerdict(
            Origin.MEASURED, "point",
            "the point declares ontosage:isSimulated false and its store declares no "
            "generated period",
        )
    if store_synthetic is False:
        return ProvenanceVerdict(
            Origin.MEASURED, "store", "the store is declared to hold real data"
        )
    return ProvenanceVerdict(
        Origin.UNKNOWN, "undeclared",
        "neither the point nor its store declares an origin; silence is not evidence of "
        "measurement",
    )


def store_boundary(registry: Dict[str, Any], store_key: str) -> Optional[str]:
    """The `measured_through` a store declares, if any.

    Reads `database_registry.yaml`'s shape — which is NOT the file
    `DataSourceRegistry` reads. That split is itself the defect this module works around:
    routing comes from `database_registry.yaml` and provenance from `datasources.yaml`,
    and the wide table appears only in the first.
    """
    if not isinstance(registry, dict):
        return None
    dbs = registry.get("databases", registry)
    spec = dbs.get(store_key) if isinstance(dbs, dict) else None
    if not isinstance(spec, dict):
        return None
    value = spec.get("measured_through")
    return str(value) if value else None
