#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Assert measured origin where it is true, so silence stops meaning "measured".

V12-04 part 1 of 3, review risk R4.

THE PROBLEM, MEASURED
---------------------
In bldg1's live graph on 2026-09-11:

    ontosage:isSimulated true   ->  1,408 points
    ontosage:isSimulated false  ->      0 points
    no declaration at all       ->  1,356 points

Nothing in this building positively asserts that a point is measured. The only provenance
signal present is the simulated flag, and silence reads as measured to any
default-permissive consumer — which is every consumer, because none of them asks.

WHICH SILENT POINTS ARE ACTUALLY MEASURED
-----------------------------------------
Grouped by the store their timeseries reference points at:

    database1            685   the WIDE sensor_data table — the real abacws sensors
    database1_floors04   522   declared `nature: synthetic` in database_registry.yaml
    database1_synth      106   declared synthetic
    narrow modality tables 43  all declared synthetic

So the 685 pointing at `database1` are the genuine physical instruments, and the rest are
silent only because their SYNTHETIC declaration lives in the registry rather than the
graph. This script declares the first group measured. It does not touch the second: their
store already says what they are, and writing it twice invites the two copies to disagree.

WHAT "MEASURED" DOES AND DOES NOT MEAN HERE
-------------------------------------------
It means A REAL PHYSICAL SENSOR EXISTS. It does NOT mean every row it has is a measurement,
and that distinction is the whole of V12-04 part 2:

    sensor_data: 697,329 rows, 2025-01-01 -> 2026-09-11
      <= 2025-03-09   576,557 rows   the real snapshot the user loaded
      >  2025-03-09   120,772 rows   generated by data-publisher (PUBLISH_WIDE=true)

The real data stops eighteen months ago, so every question about current conditions reads
generated rows from a point that is correctly declared measured. Per-POINT provenance
cannot express that; only a per-observation rule can, which is why this file is only step
one and `observation_provenance.py` is step two.

bldg1's mixed wide table is BY DESIGN and user-confirmed. Nothing here purges, relabels or
"fixes" it — the point is labelled for what it is, and the rows are judged separately.

    python scripts/declare_measured_origin.py            # write the TTL
    python scripts/declare_measured_origin.py --dry-run  # count only
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Set

import requests

REPO = Path(__file__).resolve().parent.parent

#: Stores whose points are real instruments. Read from the registry rather than hardcoded
#: would be better still, but `database_registry.yaml` marks `database1` `nature: real`
#: WITHOUT a table key, so `provenance_for_table` cannot reach it (see provenance.py).
#: Naming it here is explicit; the litmus test in the module docstring is what justifies it.
MEASURED_STORES = ("database1",)

QUERY = """
PREFIX ontosage: <http://ontosage.org/capabilities#>
PREFIX ref: <https://brickschema.org/schema/Brick/ref#>
SELECT DISTINCT ?p WHERE {
  ?p ref:hasExternalReference ?r .
  ?r ref:storedAt ?store .
  FILTER(STRENDS(STR(?store), "%s"))
  FILTER NOT EXISTS { ?p ontosage:isSimulated ?any }
}
"""


def _select(endpoint: str, query: str) -> List[str]:
    resp = requests.post(
        endpoint,
        data=query.encode("utf-8"),
        headers={
            "Content-Type": "application/sparql-query",
            "Accept": "application/sparql-results+json",
        },
        timeout=60,
    )
    resp.raise_for_status()
    return [b["p"]["value"] for b in resp.json()["results"]["bindings"]]


def main(argv: List[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--graphdb-url", default="http://localhost:7200")
    ap.add_argument("--repo", default="bldg")
    ap.add_argument("--building", default="bldg1")
    ap.add_argument("--out", default="")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    endpoint = f"{args.graphdb_url.rstrip('/')}/repositories/{args.repo}"
    subjects: Set[str] = set()
    for store in MEASURED_STORES:
        found = _select(endpoint, QUERY % store)
        print(f"  {store}: {len(found)} undeclared point(s)")
        subjects.update(found)

    if not subjects:
        print("nothing to declare — every point already states its origin")
        return 0

    print(f"total to declare measured: {len(subjects)}")
    if args.dry_run:
        return 0

    out = Path(args.out) if args.out else REPO / "input" / f"{args.building}_measured_origin.ttl"
    ns = sorted(subjects)[0].rsplit("#", 1)[0] + "#"
    lines = [
        "# Measured origin, declared explicitly so silence stops meaning 'measured'.",
        "#",
        "# GENERATED by scripts/declare_measured_origin.py (V12-04 part 1, risk R4).",
        "# Re-run it rather than hand-editing: the set is derived from which points carry a",
        "# timeseries reference into a measured store and do not already declare an origin.",
        "#",
        f"# {len(subjects)} points, all referencing {', '.join(MEASURED_STORES)} — the wide",
        "# sensor_data table, which holds this building's real physical instruments.",
        "#",
        "# THIS ASSERTS THAT A REAL SENSOR EXISTS. It does NOT assert that every row is a",
        "# measurement: sensor_data is a real snapshot (2025-01-01 -> 2025-03-09, 576,557",
        "# rows) extended by a deliberate development generator (120,772 rows and counting).",
        "# Judging an individual reading is per-observation and belongs to",
        "# orchestrator/services/observation_provenance.py, not here.",
        "",
        f"@prefix bldg: <{ns}> .",
        "@prefix ontosage: <http://ontosage.org/capabilities#> .",
        "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .",
        "",
    ]
    for iri in sorted(subjects):
        local = iri.rsplit("#", 1)[-1]
        lines.append(f'bldg:{local} ontosage:isSimulated "false"^^xsd:boolean .')
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[written] {out}  ({len(subjects)} triples)")
    print("The TTL uploader discovers bldg1_*.ttl in input/ — restart the orchestrator to load.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
