#!/usr/bin/env python3
"""
generate_spatial_topology.py — building-agnostic spatial-topology backfill.

Some ontologies (incl. the synthetic bldg2) carry sensors + spaces + floors but never
wire them together, so floor-scoped queries ("compare temperature between floor 0 and
floor 1") resolve ZERO sensors and the compare/trend pipeline deflects. This script
reconstructs the missing chain the floor-scoped resolver needs:

    ?sensor brick:hasLocation ?zone .  ?zone brick:isPartOf ?floor .  ?floor a brick:Floor

Building-agnostic derivation (no building literals):
  1. Read floors (brick:Floor) and spaces (brick:HVAC_Zone / Zone / Room / Space) from the
     ACTIVE graph.
  2. For every sensor that has a time-series id, if any dot-segment of its local name equals
     a space's local name, that space is the sensor's location (spaces are commonly encoded
     in the point name, e.g. `bldg2.ZONE.AHU01.RM001A.Zone_Air_Temp` -> RM001A). Sensors with
     no space token (building/AHU-wide points) are left unlocated — they are genuinely not
     floor-scoped.
  3. Spaces that are referenced but not yet linked to a floor are distributed evenly across
     the existing floors (sorted, block) so each floor gets a share — deterministic, so a
     re-run is idempotent.
  4. Emit `?sensor brick:hasLocation ?space` + `?space brick:isPartOf ?floor`, upload to
     GraphDB, and persist to `input/<id>_spatial_topology.ttl` (auto-loaded next boot).

Usage (host):  python scripts/generate_spatial_topology.py [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import math
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path

GRAPHDB = os.environ.get("GRAPHDB_HTTP", "http://127.0.0.1:7200")
REPO = os.environ.get("GRAPHDB_REPOSITORY", "bldg")  # single shared repo (namespace-scoped)
# No building-specific defaults: the namespace + id come from the active building's env.
# Missing BUILDING_NAMESPACE fails loudly (see main) rather than silently defaulting to one.
NS = os.environ.get("BUILDING_NAMESPACE", "")
BID = os.environ.get("BUILDING_ID", "")
BRICK = "https://brickschema.org/schema/Brick#"
REF = "https://brickschema.org/schema/Brick/ref#"


def _sparql(query: str) -> list:
    url = f"{GRAPHDB}/repositories/{REPO}?" + urllib.parse.urlencode({"query": query})
    req = urllib.request.Request(url, headers={"Accept": "application/sparql-results+json"})
    data = json.loads(urllib.request.urlopen(req, timeout=60).read())
    return data.get("results", {}).get("bindings", [])


def _local(uri: str) -> str:
    return uri.split("#")[-1].split("/")[-1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not NS:
        raise SystemExit(
            "[spatial] set BUILDING_NAMESPACE to the active building's ontology namespace "
            "(e.g. export BUILDING_NAMESPACE=$(grep ontology_namespace input/building.yaml ...)) "
            "— there is no building-specific default."
        )

    floors = sorted(
        _local(b["f"]["value"])
        for b in _sparql(
            f"PREFIX brick:<{BRICK}> SELECT ?f WHERE {{ ?f a brick:Floor . "
            f'FILTER(STRSTARTS(STR(?f),"{NS}")) }}'
        )
    )
    if not floors:
        raise SystemExit("[spatial] no brick:Floor in the active graph — nothing to link")

    spaces = {
        _local(b["z"]["value"])
        for b in _sparql(
            f"PREFIX brick:<{BRICK}> SELECT DISTINCT ?z WHERE {{ VALUES ?zt "
            f"{{ brick:HVAC_Zone brick:Zone brick:Room brick:Space }} ?z a ?zt . "
            f'FILTER(STRSTARTS(STR(?z),"{NS}")) }}'
        )
    }

    sensors = _sparql(
        f"PREFIX brick:<{BRICK}> PREFIX ref:<{REF}> SELECT DISTINCT ?s WHERE {{ "
        f"?s a ?t . ?t rdfs:subClassOf* brick:Sensor . "
        f"?s ref:hasExternalReference/ref:hasTimeseriesId ?u . "
        f'FILTER(STRSTARTS(STR(?s),"{NS}")) }}'
    )

    # sensor local -> its space local (a dot-segment that is a known space)
    sensor_space: dict = {}
    for b in sensors:
        loc = _local(b["s"]["value"])
        for seg in re.split(r"[.\-/]", loc):
            if seg in spaces:
                sensor_space[loc] = seg
                break

    used_spaces = sorted(set(sensor_space.values()))
    if not used_spaces:
        raise SystemExit("[spatial] no sensor encodes a known space token — cannot backfill")

    # distribute the referenced spaces evenly across floors (block, deterministic)
    per = math.ceil(len(used_spaces) / len(floors))
    space_floor = {sp: floors[min(i // per, len(floors) - 1)] for i, sp in enumerate(used_spaces)}

    lines = [
        f"# {BID} spatial topology — GENERATED by scripts/generate_spatial_topology.py.",
        "# Backfills sensor->space->floor so floor-scoped compare/trend resolve sensors.",
        "# Deterministic even distribution of referenced spaces across floors; re-runnable.",
        f"@prefix bldg: <{NS}> .",
        f"@prefix brick: <{BRICK}> .",
        "",
    ]
    for sp, fl in space_floor.items():
        lines.append(f"bldg:{sp} brick:isPartOf bldg:{fl} .")
    lines.append("")
    for sensor, sp in sorted(sensor_space.items()):
        lines.append(f"bldg:{sensor} brick:hasLocation bldg:{sp} .")
    ttl = "\n".join(lines) + "\n"

    print(
        f"[spatial] floors={floors} spaces_referenced={len(used_spaces)} "
        f"sensors_located={len(sensor_space)}"
    )
    dist = {fl: sum(1 for v in space_floor.values() if v == fl) for fl in floors}
    print(f"[spatial] spaces per floor = {dist}")
    if args.dry_run:
        print("---- DRY RUN (first 8 lines) ----\n" + "\n".join(lines[6:14]))
        return 0

    # Filename base = BUILDING_ID, else derive from the namespace's last token (agnostic).
    bid = BID or NS.rstrip("#/").rsplit("/", 1)[-1].rsplit("#", 1)[-1] or "building"
    out = Path("input") / f"{bid}_spatial_topology.ttl"
    out.write_text(ttl, encoding="utf-8", newline="\n")
    print(f"[spatial] wrote {out}")

    # upload to GraphDB (default graph) for immediate effect
    req = urllib.request.Request(
        f"{GRAPHDB}/repositories/{REPO}/statements",
        data=ttl.encode("utf-8"),
        headers={"Content-Type": "text/turtle"},
        method="POST",
    )
    urllib.request.urlopen(req, timeout=60)
    print("[spatial] uploaded to GraphDB (default graph)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
