#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""E5 (QA-trial plan, 2026-10-04): put the authority tiers in the GRAPH, generated from
the policy file -- TTL-first (design contract #2), not a second hand-authored copy.

"Which kind of record wins?" currently has nothing in the graph to answer from. The
three-tier rule ("bookings, access, timetables and alarms come from authorised systems,
never from environmental inference" -- rule R-7) lives in TWO Python-side places --
config/evidence_policy.yaml's source_precedence.by_kind (the policy, read live by
EvidencePolicy.source_tiers()) and precedence.py's RANK + _DEFAULT_KIND_TIER (the
conservative fallback used only when the policy declares nothing) -- and NEITHER is a
triple a SPARQL query could read.

GENERATES FROM THE POLICY, NOT HAND-AUTHORED: this script reads
config/evidence_policy.yaml's source_precedence.by_kind for the KIND -> TIER mapping and
precedence.RANK for the TIER -> integer ordering, and emits both as TTL. The policy YAML
stays the single source of truth; re-running this script after an edit to the YAML
regenerates the TTL to match, rather than the two drifting apart.

DOES NOT REUSE ontosage:SourceType: that class already exists in the schema for a
DIFFERENT taxonomy -- WHICH LANE/MECHANISM answered a question (GraphDB, Analytics,
FloorPlan, Document, ...). "booking", "sensor", "register" are a source's KIND
(EvidenceSource.kind), a different axis entirely; reusing SourceType for both would
conflate "what answered" with "how authoritative was it". Two new classes instead:
ontosage:PrecedenceTier (the ranked tier individuals) and ontosage:SourceKind (the kind
individuals, each pointing at its tier via ontosage:hasPrecedenceTier).

Output: input/<building_id>_source_precedence.ttl -- a per-building file by the existing
input/*.ttl auto-discovery convention (input_ttl_store.py), even though this content is
building-agnostic; there is no separate upload path for cross-building schema files in
this layout, and duplicating a policy-derived file per building is the existing,
low-risk mechanism rather than a new one invented for this row.

Usage:
    python scripts/generate_precedence_ttl.py                     # writes for settings.BUILDING_ID
    python scripts/generate_precedence_ttl.py --building bldg2
    python scripts/generate_precedence_ttl.py --print              # stdout only, no write
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from orchestrator.services.evidence.policy import load_policy  # noqa: E402
from orchestrator.services.evidence.precedence import RANK  # noqa: E402

NS = "http://ontosage.org/capabilities#"

_TIER_COMMENT = {
    "authoritative": "A system of record for the claim -- booking, access control, timetable, alarm, register, or a policy document standing for itself.",
    # No tracker id in this string: it ships as rdfs:comment DATA in every building's own
    # graph, not a developer comment, and a bare "BUG-194" here once collided with
    # prompt_hygiene's tracker-id stripper (test_tracker_ids_never_reach_a_reader_or_the_
    # model.py walks the real shipped TTL for exactly this). Say what the rank means, not
    # which internal ticket motivated it.
    "document_derived": "A fact LIFTED from a document (a transcribed register row), not the document's own statement of itself -- ranks below authoritative on purpose: a register can move on since the document was written.",
    "measurement": "A sensor reading, or a calculation over sensor readings.",
    "inference": "Anything derived without measuring or recording the thing itself -- a person's account, for example.",
    "unknown": "An unrecognised source kind. Can never outrank anything and can never satisfy a claim that demands authority.",
}


def _slug(name: str) -> str:
    return "".join(p.capitalize() for p in name.replace("-", "_").split("_"))


def generate_ttl(building_id: str) -> str:
    policy = load_policy(building_id)
    by_kind = policy.source_tiers()
    if not by_kind:
        # Fall back to the conservative built-in map so the TTL is never empty even
        # when no policy overlay declares anything -- matches precedence.py's own
        # fail-safe default, not a second definition of it.
        from orchestrator.services.evidence.precedence import _DEFAULT_KIND_TIER

        by_kind = dict(_DEFAULT_KIND_TIER)

    tiers_used = sorted({t for t in by_kind.values()} | set(RANK), key=lambda t: -RANK.get(t, 0))

    lines = [
        "# GENERATED by scripts/generate_precedence_ttl.py -- DO NOT HAND-EDIT.",
        "# Source of truth: config/evidence_policy.yaml (source_precedence.by_kind) +",
        "# orchestrator/services/evidence/precedence.py (RANK). Re-run the script after",
        "# changing either; this file is a rendering, not a second declaration.",
        "#",
        "# E5 (QA-trial plan, 2026-10-04): puts rule R-7 ('bookings, access, timetables and",
        "# alarms come from authorised systems, never from environmental inference') into",
        "# the graph, so 'which kind of record wins?' has triples to answer from.",
        "",
        "@prefix bldg:     <http://abacwsbuilding.cardiff.ac.uk/abacws#> .",
        f"@prefix ontosage: <{NS}> .",
        "@prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix owl:      <http://www.w3.org/2002/07/owl#> .",
        "@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .",
        "",
        "ontosage:PrecedenceTier a owl:Class ;",
        '    rdfs:label "Source precedence tier"@en ;',
        '    rdfs:comment "How authoritative a kind of evidence source is, ranked. Higher ontosage:tierRank wins a disagreement (rule R-7)."@en .',
        "",
        "ontosage:SourceKind a owl:Class ;",
        '    rdfs:label "Evidence source kind"@en ;',
        '    rdfs:comment "A kind of evidence source (booking, sensor, register, ...) -- the same vocabulary as EvidenceSource.kind in the orchestrator, linked here to its precedence tier."@en .',
        "",
        "ontosage:tierRank a owl:DatatypeProperty ;",
        "    rdfs:domain ontosage:PrecedenceTier ; rdfs:range xsd:integer ;",
        '    rdfs:label "Tier rank"@en ;',
        '    rdfs:comment "Higher wins. Values from precedence.RANK, spaced so an intermediate tier can be declared without renumbering."@en .',
        "",
        "ontosage:hasPrecedenceTier a owl:ObjectProperty ;",
        "    rdfs:domain ontosage:SourceKind ; rdfs:range ontosage:PrecedenceTier ;",
        '    rdfs:label "has precedence tier"@en .',
        "",
    ]

    for tier in tiers_used:
        rank = RANK.get(tier, 0)
        comment = _TIER_COMMENT.get(tier, "")
        lines.append(f"ontosage:Tier_{_slug(tier)} a ontosage:PrecedenceTier ;")
        lines.append(f'    rdfs:label "{tier}"@en ;')
        lines.append(f"    ontosage:tierRank {rank} ;")
        if comment:
            lines.append(f'    rdfs:comment "{comment}"@en ;')
        lines[-1] = lines[-1].rstrip(" ;") + " ."
        lines.append("")

    for kind in sorted(by_kind):
        tier = by_kind[kind]
        lines.append(f"ontosage:Kind_{_slug(kind)} a ontosage:SourceKind ;")
        lines.append(f'    rdfs:label "{kind}"@en ;')
        lines.append(f"    ontosage:hasPrecedenceTier ontosage:Tier_{_slug(tier)} .")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--building", default=None, help="Building id (default: settings.BUILDING_ID)"
    )
    parser.add_argument(
        "--print", action="store_true", dest="print_only", help="Print to stdout, do not write"
    )
    args = parser.parse_args()

    building_id = args.building
    if not building_id:
        from shared.config import settings

        building_id = settings.BUILDING_ID

    ttl = generate_ttl(building_id)
    if args.print_only:
        print(ttl)
        return 0

    out_path = REPO / "input" / f"{building_id}_source_precedence.ttl"
    out_path.write_text(ttl, encoding="utf-8")
    print(f"Wrote {out_path} ({len(ttl.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
