#!/usr/bin/env python3
"""
Generate floor 0-4 sensor artifacts for OntoSage / T10.

Produces three output files:
  1. input/bldg1_floors_0_4_sensors.ttl  — Brick sensor triples for rooms on floors 0-4
  2. mysql-dummy-publish-dev/sensor_uuids.json  — updated with floor 0-4 UUIDs
  3. data/mysql-init/add_floors_0_4_columns.sql — ALTER TABLE ADD COLUMN for MySQL sensordb

Sensors generated per room:
  - Air_Temperature_Sensor_X.YY  (brick:Air_Temperature_Sensor, decimal(6,2))
  - CO2_Level_Sensor_X.YY        (brick:CO2_Level_Sensor + CO2_Sensor, smallint(5,0))
  - Zone_Air_Humidity_Sensor_X.YY (brick:Zone_Air_Humidity_Sensor, decimal(6,2))

UUID derivation: deterministic MD5 from sensor name (same scheme as FeedRegistry._derive_uuid).
"""
from __future__ import annotations

import csv
import hashlib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

TTL_IN = REPO_ROOT / "input" / "bldg1_expanded_protege_clean.ttl"
TTL_OUT = REPO_ROOT / "input" / "bldg1_floors_0_4_sensors.ttl"
UUIDS_FILE = REPO_ROOT / "mysql-dummy-publish-dev" / "sensor_uuids.json"
CSV_FILE = REPO_ROOT / "mysql-dummy-publish-dev" / "postgresql columns.csv"
SQL_OUT = REPO_ROOT / "data" / "mysql-init" / "add_floors_0_4_columns.sql"

SENSOR_TYPES = [
    {
        "name_prefix": "Air_Temperature_Sensor",
        "label_prefix": "Air Temperature Sensor",
        "brick_classes": [
            "brick:Air_Temperature_Sensor",
            "brick:Class",
            "brick:Entity",
            "brick:Point",
            "brick:Sensor",
            "brick:Temperature_Sensor",
        ],
        "sql_dtype": "DECIMAL(6,2)",
        "csv_dtype": "decimal",
        "csv_prec": "6",
        "csv_scale": "2",
    },
    {
        "name_prefix": "CO2_Level_Sensor",
        "label_prefix": "CO2 Level Sensor",
        "brick_classes": [
            "brick:Air_Quality_Sensor",
            "brick:CO2_Level_Sensor",
            "brick:CO2_Sensor",
            "brick:Class",
            "brick:Entity",
            "brick:Point",
            "brick:Sensor",
        ],
        "sql_dtype": "SMALLINT",
        "csv_dtype": "smallint",
        "csv_prec": "5",
        "csv_scale": "0",
    },
    {
        "name_prefix": "Zone_Air_Humidity_Sensor",
        "label_prefix": "Zone Air Humidity Sensor",
        "brick_classes": [
            "brick:Class",
            "brick:Entity",
            "brick:Humidity_Sensor",
            "brick:Point",
            "brick:Relative_Humidity_Sensor",
            "brick:Sensor",
            "brick:Zone_Air_Humidity_Sensor",
        ],
        "sql_dtype": "DECIMAL(6,2)",
        "csv_dtype": "decimal",
        "csv_prec": "6",
        "csv_scale": "2",
    },
]


def make_uuid(sensor_name: str) -> str:
    """Deterministic UUID from sensor name (MD5, same as FeedRegistry._derive_uuid)."""
    digest = hashlib.md5(sensor_name.encode()).hexdigest()
    return f"{digest[:8]}-{digest[8:12]}-{digest[12:16]}-{digest[16:20]}-{digest[20:]}"


def extract_rooms(ttl_text: str) -> list[str]:
    """Return sorted list of room suffixes like '0.01', '1.04', ... for floors 0-4."""
    raw = sorted(set(re.findall(r"bldg:Room([0-4]\.\d+)", ttl_text)))
    return raw


def build_sensor_id(name_prefix: str, room_suffix: str) -> str:
    """e.g. 'Air_Temperature_Sensor_0.01'"""
    return f"{name_prefix}_{room_suffix}"


def build_ttl(rooms: list[str]) -> str:
    lines = []
    lines.append(
        "# Floor 0-4 sensor instances — generated by scripts/generate_floors_0_4_sensors.py"
    )
    lines.append(
        "# Synthetic sensors; rdfs:comment marks them as auto-generated for provenance."
    )
    lines.append(
        "# Named graph: <http://abacwsbuilding.cardiff.ac.uk/abacws/floors_0_4_sensors>"
    )
    lines.append("")
    lines.append("@prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .")
    lines.append("@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .")
    lines.append("@prefix owl:    <http://www.w3.org/2002/07/owl#> .")
    lines.append("@prefix brick:  <https://brickschema.org/schema/Brick#> .")
    lines.append("@prefix ref:    <https://brickschema.org/schema/Brick/ref#> .")
    lines.append("@prefix ashrae: <http://data.ashrae.org/standard223#> .")
    lines.append("@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .")
    lines.append(
        "@prefix bldg:   <http://abacwsbuilding.cardiff.ac.uk/abacws#> ."
    )
    lines.append("")

    bnode_counter = 90000  # start well above genid values in the main TTL

    for room_suffix in rooms:
        floor = room_suffix.split(".")[0]  # "0", "1", ...
        for stype in SENSOR_TYPES:
            sensor_id = build_sensor_id(stype["name_prefix"], room_suffix)
            uuid = make_uuid(sensor_id)
            bnode = f"_:gen_f{floor}_{sensor_id.replace('.', '_')}"
            label = f"{stype['label_prefix']} installed-node {room_suffix}"

            # Sensor individual
            brick_type_list = " ,\n".join(
                f"                             {c}" for c in stype["brick_classes"]
            )
            lines.append(f"bldg:{sensor_id} rdf:type owl:NamedIndividual ,")
            lines.append(f"{brick_type_list} ;")
            lines.append(
                f'                    ashrae:hasExternalReference {bnode} ;'
            )
            lines.append(
                f"                    brick:hasLocation bldg:Room{room_suffix} ;"
            )
            lines.append(
                f'                    ref:hasExternalReference {bnode} ;'
            )
            lines.append(
                f'                    rdfs:comment "synthetic-floor0-4"^^xsd:string ;'
            )
            lines.append(f'                    rdfs:label "{label}"@en .')
            lines.append("")

            # Blank node with TimeseriesId
            lines.append(
                f"{bnode} rdf:type ashrae:ExternalReference ,"
            )
            lines.append(
                f"             ref:ExternalReference ,"
            )
            lines.append(
                f"             ref:TimeseriesReference ;"
            )
            lines.append(
                f'        ref:hasTimeseriesId "{uuid}" ;'
            )
            lines.append(f"        ref:storedAt bldg:database1 .")
            lines.append("")

            bnode_counter += 1

    return "\n".join(lines)


def update_sensor_uuids(rooms: list[str]) -> dict[str, str]:
    """Load existing sensor_uuids.json, add floor 0-4 sensors, return updated dict."""
    with open(UUIDS_FILE, encoding="utf-8") as f:
        uuids: dict[str, str] = json.load(f)

    added = 0
    for room_suffix in rooms:
        for stype in SENSOR_TYPES:
            sensor_id = build_sensor_id(stype["name_prefix"], room_suffix)
            if sensor_id not in uuids:
                uuids[sensor_id] = make_uuid(sensor_id)
                added += 1

    print(f"[gen] Added {added} new sensor UUIDs to sensor_uuids.json")
    return uuids


def update_csv(rooms: list[str]) -> None:
    """Append new floor 0-4 sensor columns to postgresql columns.csv."""
    # Read existing
    with open(CSV_FILE, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        existing_rows = list(reader)
        fieldnames = reader.fieldnames or []

    existing_uuids = {r["COLUMN_NAME"] for r in existing_rows}
    max_ordinal = max(int(r["ORDINAL_POSITION"]) for r in existing_rows)

    new_rows = []
    for room_suffix in rooms:
        for stype in SENSOR_TYPES:
            sensor_id = build_sensor_id(stype["name_prefix"], room_suffix)
            uuid = make_uuid(sensor_id)
            if uuid in existing_uuids:
                continue
            max_ordinal += 1
            new_rows.append(
                {
                    "TABLE_SCHEMA": "sensordb",
                    "TABLE_NAME": "sensor_data",
                    "COLUMN_NAME": uuid,
                    "ORDINAL_POSITION": str(max_ordinal),
                    "DATA_TYPE": stype["csv_dtype"],
                    "CHARACTER_MAXIMUM_LENGTH": "NULL",
                    "NUMERIC_PRECISION": stype["csv_prec"],
                    "NUMERIC_SCALE": stype["csv_scale"],
                    "IS_NULLABLE": "YES",
                    "COLUMN_DEFAULT": "NULL",
                }
            )

    if not new_rows:
        print("[gen] CSV: no new rows to add")
        return

    with open(CSV_FILE, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(existing_rows)
        writer.writerows(new_rows)

    print(f"[gen] Added {len(new_rows)} rows to postgresql columns.csv")


def build_sql(rooms: list[str]) -> str:
    lines = [
        "-- ALTER TABLE statements to add floor 0-4 sensor columns to sensordb.sensor_data",
        "-- Generated by scripts/generate_floors_0_4_sensors.py",
        "-- Run once against the running MySQL instance when promoting floors 0-4 sensors.",
        "USE sensordb;",
        "",
    ]
    for room_suffix in rooms:
        for stype in SENSOR_TYPES:
            sensor_id = build_sensor_id(stype["name_prefix"], room_suffix)
            uuid = make_uuid(sensor_id)
            lines.append(
                f"ALTER TABLE `sensor_data` ADD COLUMN IF NOT EXISTS "
                f"`{uuid}` {stype['sql_dtype']} NULL COMMENT '{sensor_id}';"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    print(f"[gen] Reading rooms from {TTL_IN}")
    ttl_text = TTL_IN.read_text(encoding="utf-8")
    rooms = extract_rooms(ttl_text)
    print(f"[gen] Found {len(rooms)} rooms on floors 0-4")

    # 1. Write TTL
    ttl_content = build_ttl(rooms)
    TTL_OUT.write_text(ttl_content, encoding="utf-8")
    print(f"[gen] Wrote {TTL_OUT}")

    # 2. Update sensor_uuids.json
    updated_uuids = update_sensor_uuids(rooms)
    UUIDS_FILE.write_text(json.dumps(updated_uuids, indent=2), encoding="utf-8")
    print(f"[gen] Wrote {UUIDS_FILE} ({len(updated_uuids)} total sensors)")

    # 3. Update postgresql columns.csv
    update_csv(rooms)
    print(f"[gen] Updated {CSV_FILE}")

    # 4. Write SQL
    sql_content = build_sql(rooms)
    SQL_OUT.write_text(sql_content, encoding="utf-8")
    print(f"[gen] Wrote {SQL_OUT}")

    total_sensors = len(rooms) * len(SENSOR_TYPES)
    print(
        f"[gen] Done. {total_sensors} sensors across {len(rooms)} rooms, "
        f"3 types per room."
    )


if __name__ == "__main__":
    main()
