#!/usr/bin/env python
"""Generate bldg4 — a wholly fictional building for GUI onboarding testing.

**What bldg4 is for.** TODO-072's thesis is that a building can be onboarded
end-to-end through the Admin Console: identity, ontology, datasource, documents,
floor plans, with nothing hand-placed in ``input/``. Proving it needs a building
whose files exist but are NOT already installed — so bldg4's files live in
``bldg4/`` and are uploaded through the console, never copied into ``input/``.

**It is fictional, and says so everywhere.** ``provenance.nature: synthetic``, a
namespace under ``example.org``, and a name nobody could mistake for an estate:
no room, sensor or reading corresponds to anything real. That matters because
bldg1 is a real building and this project has already had to remove a simulated
health claim made about one.

**Small on purpose.** Three floors, eighteen rooms, four modalities. Large enough
that coverage, routing and the evidence chokepoint all have something to work on;
small enough that a person can upload the whole set by hand through a browser and
still read what they uploaded.

Deterministic: same inputs, same UUIDs, same file bytes. Re-running is a no-op, so
a half-finished onboarding test can be restarted from a known state.

Run:
  python scripts/generate_bldg4_fixture.py
  python scripts/generate_bldg4_fixture.py --out bldg4 --force
"""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path
from typing import Dict, List

REPO = Path(__file__).resolve().parents[1]

BUILDING_ID = "bldg4"
BUILDING_NAME = "Northgate Test House (bldg4)"
NAMESPACE = "http://example.org/ontosage/bldg4#"
#: Fixed so every regenerated UUID is identical. A fixture whose ids move cannot be
#: used to check that an upload landed.
UUID_SEED = uuid.UUID("4b1d0000-0000-4000-8000-00000000b1d4")

FLOORS = (0, 1, 2)
ROOMS_PER_FLOOR = 6

#: (modality key, Brick class, unit token, room-suffix that gets one)
MODALITIES = (
    ("temperature", "Zone_Air_Temperature_Sensor", "degC", "all"),
    ("humidity", "Relative_Humidity_Sensor", "percent", "all"),
    ("co2", "CO2_Level_Sensor", "ppm", "even"),
    ("occupancy", "Occupancy_Count_Sensor", "persons", "even"),
)

ROOM_KINDS = (
    ("Office", "brick:Office"),
    ("Meeting_Room", "brick:Conference_Room"),
    ("Laboratory", "brick:Laboratory"),
    ("Office", "brick:Office"),
    ("Kitchen", "brick:Kitchen"),
    ("Store", "brick:Storage_Room"),
)


def point_uuid(*parts: str) -> str:
    return str(uuid.uuid5(UUID_SEED, ":".join(parts)))


def rooms() -> List[Dict[str, str]]:
    out = []
    for floor in FLOORS:
        for n in range(1, ROOMS_PER_FLOOR + 1):
            kind, cls = ROOM_KINDS[(n - 1) % len(ROOM_KINDS)]
            out.append(
                {
                    "local": f"Room_{floor}_{n:02d}",
                    "label": f"Room {floor}.{n:02d} - {kind.replace('_', ' ')}",
                    "cls": cls,
                    "floor": floor,
                    "n": n,
                }
            )
    return out


def abox() -> str:
    lines = [
        f"# {BUILDING_NAME} - wholly fictional building for GUI onboarding testing.",
        "#",
        "# GENERATED by scripts/generate_bldg4_fixture.py. Every room, sensor and reading",
        "# is invented: nothing here corresponds to any real building, and the namespace",
        "# is under example.org so it cannot collide with a real estate's.",
        "#",
        "# Uploaded through the Admin Console rather than copied into input/ -- that is the",
        "# whole point of this fixture (TODO-072).",
        "",
        "@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .",
        "@prefix brick: <https://brickschema.org/schema/Brick#> .",
        "@prefix ref:   <https://brickschema.org/schema/Brick/ref#> .",
        "@prefix qudt:  <http://qudt.org/schema/qudt/> .",
        "@prefix ontosage: <http://ontosage.org/capabilities#> .",
        f"@prefix bldg:  <{NAMESPACE}> .",
        "",
        "bldg:NorthgateTestHouse a brick:Building ;",
        f'    rdfs:label "{BUILDING_NAME}" ;',
        '    rdfs:comment "Fictional. Generated for onboarding tests; corresponds to no real building." .',
        "",
    ]
    for floor in FLOORS:
        lines += [
            f"bldg:Floor{floor} a brick:Floor ;",
            f'    rdfs:label "Floor {floor}" ;',
            "    brick:isPartOf bldg:NorthgateTestHouse .",
            "",
        ]
    for r in rooms():
        lines += [
            f"bldg:{r['local']} a {r['cls']} ;",
            f'    rdfs:label "{r["label"]}" ;',
            f"    brick:isPartOf bldg:Floor{r['floor']} .",
            "",
        ]
    for modality, cls, unit, which in MODALITIES:
        for r in rooms():
            if which == "even" and r["n"] % 2:
                continue
            local = f"{modality.capitalize()}_{r['local']}"
            uid = point_uuid(BUILDING_ID, modality, r["local"])
            lines += [
                f"bldg:{local} a brick:{cls} ;",
                f'    rdfs:label "{modality.capitalize()} - {r["label"]}" ;',
                f"    brick:hasLocation bldg:{r['local']} ;",
                f'    brick:hasUnit "{unit}" ;',
                # Every readable point declares its own provenance. building.yaml
                # already says the BUILDING is synthetic, but the per-point rule is
                # stricter and right: a point carrying a timeseries reference is
                # readable, and an answer citing it must be able to say the reading
                # is synthetic without going and reading building.yaml. The existing
                # suite caught this fixture violating it.
                '    ontosage:isSimulated "true"^^xsd:boolean ;',
                "    ref:hasExternalReference [",
                "        a ref:TimeseriesReference ;",
                f'        ref:hasTimeseriesId "{uid}" ;',
                "        ref:storedAt bldg:database4",
                "    ] .",
                "",
            ]
    return "\n".join(lines)


def capabilities() -> str:
    return f"""# Amenities and knowledge topics for {BUILDING_NAME} (OCBV).
#
# GENERATED. Fictional, like everything else in this fixture. Present so the
# capability lane has something to answer during an onboarding test.

@prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .
@prefix ontosage: <http://ontosage.org/capabilities#> .
@prefix bldg:     <{NAMESPACE}> .

bldg:Amenity_Kitchen_Floor1 a ontosage:Amenity ;
    rdfs:label "Shared kitchen"@en ;
    ontosage:layTerms "kitchen, tea, coffee, microwave, kettle, break room" ;
    ontosage:locatedIn bldg:Room_1_05 ;
    ontosage:onFloor "Floor1" ;
    ontosage:locationText "Shared kitchen in Room 1.05 (floor Floor1)" ;
    ontosage:answerText "There is a shared kitchen in Room 1.05 on floor 1." ;
    ontosage:isSimulated "true"^^xsd:boolean .

bldg:Amenity_DrinkingWater_Floor0 a ontosage:Amenity ;
    rdfs:label "Drinking water point"@en ;
    ontosage:layTerms "water, drinking water, bottle refill, refill station, fill my bottle" ;
    ontosage:locatedIn bldg:Room_0_05 ;
    ontosage:onFloor "Floor0" ;
    ontosage:locationText "Drinking water point in Room 0.05 (floor Floor0)" ;
    ontosage:answerText "There is a drinking water point in Room 0.05 on floor 0." ;
    ontosage:isSimulated "true"^^xsd:boolean .

bldg:Topic_ReportFault a ontosage:KnowledgeTopic , ontosage:Procedure ;
    rdfs:label "Reporting a fault"@en ;
    ontosage:capabilityCategory "PROCEDURE" ;
    ontosage:layTerms "report a fault, something is broken, report a problem, maintenance request" ;
    ontosage:answerText "Faults are reported to the (fictional) Northgate facilities desk." ;
    ontosage:steps "Note the room and floor; Describe what is wrong; Send it to the facilities desk" ;
    ontosage:isSimulated "true"^^xsd:boolean .

bldg:Topic_OpeningHours a ontosage:KnowledgeTopic , ontosage:InformationTopic ;
    rdfs:label "Opening hours"@en ;
    ontosage:capabilityCategory "INFORMATION" ;
    ontosage:layTerms "opening hours, when is the building open, access hours, closing time" ;
    ontosage:answerText "Northgate Test House is open 07:00-19:00 on weekdays and closed at weekends." ;
    ontosage:isSimulated "true"^^xsd:boolean .
"""


def building_yaml() -> str:
    return f"""# Building identity: {BUILDING_ID}
#
# ontology_namespace MUST match the `@prefix bldg:` in {BUILDING_ID}.ttl exactly --
# the startup TTL validator hard-fails the boot on a mismatch, so a silently-empty
# knowledge graph is impossible.

building_id: {BUILDING_ID}
building_name: "{BUILDING_NAME}"
ontology_namespace: "{NAMESPACE}"
ontology_prefix: bldg
timezone: "Europe/London"

provenance:
  nature: synthetic
  note: >-
    Wholly fictional. Invented for GUI onboarding testing (TODO-072): every room,
    sensor and reading is generated and nothing corresponds to a real building.
    Deliberately NOT a real estate -- a simulated claim about a real building is a
    mistake this project has already had to undo once.

capability_routing:
  enabled: true
  embedding_model: auto
  threshold: 0.56
  override_min: 0.60
  top_k: 5
  fallback_on_qdrant_failure: skip

actuation:
  driver: none
  points_writable: []
"""


def database_registry() -> str:
    return f"""# Time-series routing for {BUILDING_ID}.
#
# The TTL says `ref:storedAt bldg:database4`; this maps that key to a backend.
# Points at the same MySQL container the other buildings use, with its own
# database name, so onboarding does not need new infrastructure.

databases:
  database4:
    type: mysql
    host: ${{MYSQL_HOST:-host.docker.internal}}
    port: ${{MYSQL_PORT:-3306}}
    database: ${{MYSQL_DATABASE:-bldg4db}}
    user: ${{MYSQL_USER:-ontosage}}
    password: ${{MYSQL_PASSWORD}}
    table: sensor_readings
    schema: narrow
    columns:
      uuid: uuid
      timestamp: datetime
      value: value
    nature: synthetic
    note: "Generated readings for a fictional building."
"""


def readme(n_rooms: int, n_points: int) -> str:
    return f"""# {BUILDING_NAME}

A **wholly fictional** building, generated by
`scripts/generate_bldg4_fixture.py`. Nothing here corresponds to a real estate:
the namespace is under `example.org`, `provenance.nature` is `synthetic`, and
every room, sensor and reading is invented.

## What it is for

TODO-072's thesis: a building can be onboarded end to end **through the Admin
Console** — identity, ontology, datasource, documents, floor plans — with nothing
hand-placed in `input/`.

That is why these files live in `bldg4/` and **must not be copied into `input/`**.
Copying them would test the file loader, which already works, instead of the
console, which is the claim under test.

## Contents

| file | what it is |
|---|---|
| `building.yaml` | identity + provenance |
| `bldg4.ttl` | {n_rooms} rooms across {len(FLOORS)} floors, {n_points} sensors with timeseries references |
| `bldg4_capabilities.ttl` | two amenities, two knowledge topics |
| `database_registry.yaml` | routes `bldg:database4` to MySQL |
| `documents/building_guide.md` | one uploadable document |

## Onboarding it through the console

1. Start the stack with an **empty** `input/` — that is what
   `docker-compose.bldgtest.yml` and `.env4` are for.
2. Admin → **Onboarding**. Each step reads its readiness from the LIVE system —
   spaces in the graph, declared sensors against UUIDs that actually have rows,
   the share of floor-plan spaces linked to an IRI — never from a checklist.
3. Upload `bldg4.ttl` and `bldg4_capabilities.ttl` (Ontology tab), register the
   datasource, then upload the document.

`identity` and `ontology` are blocking; the rest narrow what can be answered
rather than breaking it. A step that stays red after an upload is the finding —
that is the point of running this at all.

## Questions worth asking afterwards

- *"How many rooms are on floor 1?"* — spatial/metadata
- *"What is the temperature in Room 1.03?"* — the full sensor path
- *"Where can I fill my water bottle?"* — the capability lane
- *"How do I report a fault?"* — a knowledge topic
- *"How many desks are there?"* — should say the building does not model desks,
  not "0"
"""


def guide_doc() -> str:
    return f"""# {BUILDING_NAME} - building guide

*Fictional document, generated for onboarding tests. Nothing in it describes a
real building.*

## Access

The building is open 07:00-19:00 Monday to Friday and closed at weekends.
Out-of-hours access is by arrangement with the (fictional) facilities desk.

## Floors

- **Floor 0** - reception, stores and a drinking water point in Room 0.05.
- **Floor 1** - offices, laboratories and the shared kitchen in Room 1.05.
- **Floor 2** - offices and meeting rooms.

## Environmental conditions

Offices and laboratories are monitored for temperature and relative humidity.
Even-numbered rooms additionally carry CO2 and occupancy sensing.

## Reporting a fault

Note the room and floor, describe what is wrong, and send it to the facilities
desk. A report that does not say where it is cannot be actioned.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=BUILDING_ID)
    ap.add_argument("--force", action="store_true", help="overwrite an existing directory")
    args = ap.parse_args()

    out = REPO / args.out
    if out.exists() and not args.force:
        existing = sorted(p.name for p in out.iterdir())
        print(f"{out} already exists ({len(existing)} entries). Re-run with --force to rebuild.")
        return 1
    (out / "documents").mkdir(parents=True, exist_ok=True)

    rs = rooms()
    n_points = sum(
        1
        for modality, _c, _u, which in MODALITIES
        for r in rs
        if not (which == "even" and r["n"] % 2)
    )

    files = {
        "building.yaml": building_yaml(),
        f"{BUILDING_ID}.ttl": abox(),
        f"{BUILDING_ID}_capabilities.ttl": capabilities(),
        "database_registry.yaml": database_registry(),
        "README.md": readme(len(rs), n_points),
        "documents/building_guide.md": guide_doc(),
    }
    for name, body in files.items():
        (out / name).write_text(body, encoding="utf-8")

    # The uuid list, so an onboarding test can seed rows for exactly these points.
    uids = {
        f"{modality}:{r['local']}": point_uuid(BUILDING_ID, modality, r["local"])
        for modality, _c, _u, which in MODALITIES
        for r in rs
        if not (which == "even" and r["n"] % 2)
    }
    (out / f"{BUILDING_ID}_uuids.json").write_text(
        json.dumps(uids, indent=2, sort_keys=True), encoding="utf-8"
    )

    print(f"wrote {out}/ - {len(rs)} rooms, {n_points} sensors, {len(files) + 1} files")
    for name in sorted(files):
        print(f"   {name}")
    print(f"   {BUILDING_ID}_uuids.json")

    try:
        import rdflib

        for ttl in sorted(out.glob("*.ttl")):
            g = rdflib.Graph()
            g.parse(str(ttl), format="turtle")
            print(f"   {ttl.name}: {len(g)} triples parse OK")
    except ImportError:  # pragma: no cover
        print("   (rdflib not installed - skipped the parse check)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
