#!/usr/bin/env python
"""Publish MEASURED forecast skill into the building's graph (CAVEAT-324).

``ontosage:ForecastSkill`` and its four properties — ``backtestMAE``,
``backtestMAPE``, ``ciCoverage80``, ``horizonHours`` — were declared in the OCBV
schema and referenced by nothing. The schema says what they are for: *"Cited in
every forecast answer; makes 'how good are your forecasts?' SPARQL-answerable."*
Neither was true.

The numbers already exist. ``volumes/<building>/artifacts/forecast_skill.json`` is
written by the grader from walk-forward backtesting and read by
``forecasting/calibration.py`` to widen confidence bands. This publishes the same
cells into the graph so a question can reach them, and so a forecast answer can
cite its own measured accuracy instead of asserting confidence.

**Nothing here measures anything.** It transcribes what the grader measured,
carrying ``graded_at`` through as ``skillMeasuredAt`` so a stale cell is visible
as stale rather than passing for current. A modality with no measured cell gets
no triple — an absent skill record is the honest state, and inventing a plausible
MAE for an unmeasured modality would be exactly the fabrication the evidence
discipline exists to prevent.

Run:
  python scripts/publish_forecast_skill.py --building-id bldg2
  python scripts/publish_forecast_skill.py --building-id bldg2 --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parents[1]

#: Horizon keys look like "1h", "6h", "24h". Anything unparseable is skipped with a
#: note rather than guessed at.
_HORIZON_RE = re.compile(r"^(\d+(?:\.\d+)?)\s*h$", re.IGNORECASE)


def registry_path(building_id: str) -> Optional[Path]:
    for p in (
        REPO / "volumes" / building_id / "artifacts" / "forecast_skill.json",
        REPO / "volumes" / "artifacts" / "forecast_skill.json",
    ):
        if p.is_file():
            return p
    return None


def building_dir(building_id: str) -> Optional[Path]:
    """The building's TTL directory, active (input/) or parked (<id>/)."""
    active = REPO / "input"
    if (active / "building.yaml").is_file():
        try:
            if building_id in (active / "building.yaml").read_text(encoding="utf-8"):
                return active
        except OSError:  # pragma: no cover
            pass
    parked = REPO / building_id
    return parked if parked.is_dir() else None


def _namespace_of(bldg_dir: Path) -> str:
    """The building's own namespace, read from its TTLs — never assumed."""
    for ttl in sorted(bldg_dir.glob("*.ttl")):
        if ttl.name.lower().startswith("brick"):
            continue
        m = re.search(
            r"@prefix\s+bldg:\s*<([^>]+)>", ttl.read_text(encoding="utf-8", errors="replace")
        )
        if m:
            return m.group(1)
    raise SystemExit(f"could not find a bldg: prefix in {bldg_dir}")


def cells(registry: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Flatten {modality: {horizon: metrics}} into one row per measured cell."""
    out: List[Dict[str, Any]] = []
    for modality, horizons in sorted((registry or {}).items()):
        if not isinstance(horizons, dict):
            continue
        for hkey, metrics in sorted(horizons.items()):
            m = _HORIZON_RE.match(str(hkey))
            if not m or not isinstance(metrics, dict):
                print(f"  skipped {modality}/{hkey}: unparseable horizon or metrics")
                continue
            out.append(
                {
                    "modality": modality,
                    "horizon_h": float(m.group(1)),
                    "mae": metrics.get("mae"),
                    "mape": metrics.get("mape"),
                    "ci80": metrics.get("ci80_coverage"),
                    "measured_at": metrics.get("graded_at"),
                    "n_fits": metrics.get("n_fits"),
                }
            )
    return out


def render(building_id: str, namespace: str, rows: List[Dict[str, Any]]) -> str:
    lines = [
        f"# Measured forecast skill for {building_id} (OCBV Module J, CAVEAT-324).",
        "#",
        "# GENERATED by scripts/publish_forecast_skill.py from",
        f"# volumes/{building_id}/artifacts/forecast_skill.json, which the forecast grader",
        "# writes from walk-forward backtesting. NOTHING HERE IS MEASURED BY THIS SCRIPT:",
        "# it transcribes what the grader measured, and carries graded_at through as",
        "# ontosage:skillMeasuredAt so a stale cell reads as stale rather than as current.",
        "#",
        "# A modality with no measured cell gets no triple. An absent skill record is the",
        "# honest state; inventing a plausible MAE for an unmeasured modality is exactly",
        "# the fabrication the evidence discipline exists to prevent.",
        "",
        "@prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .",
        "@prefix ontosage: <http://ontosage.org/capabilities#> .",
        f"@prefix bldg:     <{namespace}> .",
        "",
    ]
    for r in rows:
        local = f"ForecastSkill_{r['modality']}_{r['horizon_h']:g}h".replace(".", "_")
        lines.append(f"bldg:{local} a ontosage:ForecastSkill ;")
        lines.append(
            f'    rdfs:label "Forecast skill - {r["modality"]} at {r["horizon_h"]:g}h"@en ;'
        )
        lines.append(f'    ontosage:skillOf "{r["modality"]}" ;')
        lines.append(f"    ontosage:horizonHours {r['horizon_h']:g} ;")
        for prop, val in (
            ("backtestMAE", r["mae"]),
            ("backtestMAPE", r["mape"]),
            ("ciCoverage80", r["ci80"]),
        ):
            if isinstance(val, (int, float)):
                lines.append(f"    ontosage:{prop} {float(val):g} ;")
        if r["measured_at"]:
            lines.append(f'    ontosage:skillMeasuredAt "{r["measured_at"]}"^^xsd:dateTime ;')
        # The fit count is what makes a coverage figure readable: 0.83 from six fits
        # is a different claim from 0.83 from six hundred.
        if isinstance(r["n_fits"], int):
            lines.append(f'    rdfs:comment "Measured over {r["n_fits"]} walk-forward fit(s)." ;')
        lines[-1] = lines[-1].rstrip(" ;") + " ."
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Publish measured forecast skill as TTL.")
    ap.add_argument("--building-id", required=True)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    reg_path = registry_path(args.building_id)
    if reg_path is None:
        print(
            f"No skill registry for {args.building_id}. Nothing is published: skill that has\n"
            f"not been measured must not appear in the graph. Run the forecast grader first."
        )
        return 1
    bldg_dir = building_dir(args.building_id)
    if bldg_dir is None:
        print(
            f"No TTL directory for {args.building_id} (looked for input/ and {args.building_id}/)"
        )
        return 1

    registry = json.loads(reg_path.read_text(encoding="utf-8"))
    rows = cells(registry)
    if not rows:
        print("Registry holds no parseable cells; nothing published.")
        return 1
    ttl = render(args.building_id, _namespace_of(bldg_dir), rows)
    out = bldg_dir / f"{args.building_id}_forecast_skill.ttl"

    print(f"{len(rows)} measured cell(s) from {reg_path.relative_to(REPO)}:")
    for r in rows:
        print(
            f"  {r['modality']:<12} {r['horizon_h']:>5g}h  MAE={r['mae']}  "
            f"MAPE={r['mape']}  CI80={r['ci80']}"
        )
    if args.dry_run:
        print(f"\nDRY RUN — would write {out}")
        return 0
    out.write_text(ttl, encoding="utf-8")
    print(f"\nwrote {out}")
    try:
        import rdflib

        g = rdflib.Graph()
        g.parse(str(out), format="turtle")
        print(f"  {len(g)} triples parse OK")
    except ImportError:  # pragma: no cover
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
