#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Find, and optionally remove, stored readings that are not physically possible.

WHAT THIS IS FOR
----------------
`ontology/measurand_kinds.ttl` declares, per quantity, the range a reading can physically
take -- `ontosage:physicalMin` / `physicalMax`, deliberately far wider than any comfort or
compliance band. A value outside that range is not a low reading or a high one. It is not a
reading: almost always the stream is carrying a different quantity's scale.

Measured on the active building 2026-09-06: 4,470,907 rows attributed to CO2 sensors held
values between 0 and 150. Outdoor air is about 420 ppm. The publisher's value-range map had
typed those 174 sensors by a Brick SUPERCLASS (`Air_Quality_Sensor`, which covers CO2, TVOC
and particulates alike) and given them an air-quality-INDEX band. The building answered
"Floor 1's average CO2 (157 ppm) is higher than Floor 3's (111 ppm)" and recommended an
HVAC upgrade on the strength of it.

WHY DELETE RATHER THAN RESCALE
------------------------------
An index and a concentration are related by no transform anyone measured. Rescaling 0-150
onto 400-1200 would produce seven weeks of history that looks like carbon dioxide, was never
generated by any declared process, and is indistinguishable in the table from a measurement.
That is the thing design contract 4 forbids, and a table's `nature: synthetic` label does
not reach it -- the label says the DATA is generated, not that any number may be written
into it.

Deleting costs the history. A question about last week then answers "no data", which is
true, and the corrected publisher rebuilds from now. A wrong answer is worse than no answer;
that is the whole premise of this system.

WHAT IT WILL NOT TOUCH
----------------------
**A UNIT ERROR IS NOT AN EVENT, AND ONLY THE FIRST IS SAFE TO DELETE.**

The first version of this script deleted every out-of-band row it found. Run as written it
would have destroyed the anomaly-detection measurement fixtures: `scripts/grade_anomalies.py
inject` plants labelled faults by writing sentinel values -- `777.7` for a stuck sensor,
`99999` for a spike, `value+500` for a drift -- precisely BECAUSE they are implausible. A
purge that removed them would have deleted the faults, left the labels, and made every
detector look like it had missed everything. That is the fourth time in this project's
history that a measurement apparatus was about to be broken by a fix to the thing it
measures.

So the rule is a SHARE, not a value. A stream where nearly every row is out of band is a
unit error: the instrument never measured that quantity on that scale. A stream where a
minority is out of band contains events -- injected faults, real spikes, a sensor failing --
and those rows are the signal, not the noise. Default threshold 0.95, adjustable, and a
stream below it is reported and left alone.

Two further limits. Only backends declared `nature: synthetic` in the building's own
datasource registry are eligible, and only with `--apply`. A source declared real is
REPORTED and never modified, whatever its values look like: an implausible reading from a
real instrument is a fault to investigate, and deleting it destroys the evidence.

    python scripts/purge_implausible_readings.py                    # report only
    python scripts/purge_implausible_readings.py --table sensor_data_floors04 --apply
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import requests  # noqa: E402

from shared.db_clock import UTC_SESSION_INIT  # noqa: E402

GRAPHDB = "http://localhost:7200/repositories/bldg"

#: uuid -> (measurand label, physicalMin, physicalMax, unit, storedAt key)
_BANDS = """
PREFIX ref: <https://brickschema.org/schema/Brick/ref#>
PREFIX o:   <http://ontosage.org/capabilities#>
SELECT ?uuid ?store (SAMPLE(?m) AS ?kind) (SAMPLE(?lo) AS ?lo) (SAMPLE(?hi) AS ?hi)
       (SAMPLE(?u) AS ?unit) WHERE {
  ?s ref:hasExternalReference ?r .
  ?r ref:hasTimeseriesId ?uuid ; ref:storedAt ?store .
  ?s a ?cls . ?cls o:measuresQuantityKind ?m .
  ?m o:physicalMin ?lo ; o:physicalMax ?hi .
  OPTIONAL { ?m o:physicalUnit ?u }
} GROUP BY ?uuid ?store
"""


def _sparql(query: str, endpoint: str) -> List[dict]:
    r = requests.post(
        endpoint,
        data=query.encode("utf-8"),
        headers={
            "Content-Type": "application/sparql-query",
            "Accept": "application/sparql-results+json",
        },
        timeout=300,
    )
    r.raise_for_status()
    return r.json().get("results", {}).get("bindings", [])


def _local(iri: str) -> str:
    return iri.rsplit("#", 1)[-1].rsplit("/", 1)[-1]


def _env(key: str, default: str = "") -> str:
    p = REPO / ".env"
    if p.exists():
        for line in p.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if s and not s.startswith("#") and s.split("=", 1)[0].strip() == key:
                return s.split("=", 1)[1].split("#", 1)[0].strip().strip('"').strip("'")
    return default


def _registry(path: Path) -> Dict[str, dict]:
    import yaml

    if not path.exists():
        return {}
    cfg = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    dbs = cfg.get("databases") or cfg
    return {k: v for k, v in (dbs or {}).items() if isinstance(v, dict)}


def main(argv: List[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--endpoint", default=GRAPHDB)
    ap.add_argument("--input", default="input")
    ap.add_argument("--table", default="", help="limit to one narrow table")
    ap.add_argument(
        "--apply",
        action="store_true",
        help="DELETE the out-of-band rows (synthetic sources only)",
    )
    ap.add_argument(
        "--min-share",
        type=float,
        default=0.95,
        help=(
            "only purge a stream when at least this share of its rows is out of band. "
            "Below it the out-of-band rows are EVENTS -- injected faults, spikes, a failing "
            "sensor -- and deleting them destroys the signal. Default 0.95."
        ),
    )
    args = ap.parse_args(argv)

    import pymysql

    reg = _registry(REPO / args.input / "database_registry.yaml")
    bands = _sparql(_BANDS, args.endpoint)
    if not bands:
        print("no sensor resolves to a declared physical band; is measurand_kinds.ttl loaded?")
        return 1

    # table -> {uuid: (kind, lo, hi, unit)}, restricted to narrow backends
    by_table: Dict[str, Dict[str, tuple]] = defaultdict(dict)
    nature: Dict[str, str] = {}
    for b in bands:
        key = _local(b["store"]["value"])
        spec = reg.get(key)
        if not spec or not str(spec.get("type", "")).endswith("narrow"):
            continue
        table = str(spec.get("table") or key)
        nature[table] = str(spec.get("nature", "unknown"))
        by_table[table][b["uuid"]["value"]] = (
            _local(b["kind"]["value"]),
            float(b["lo"]["value"]),
            float(b["hi"]["value"]),
            (b.get("unit") or {}).get("value", ""),
        )

    if args.table:
        by_table = {k: v for k, v in by_table.items() if k == args.table}
        if not by_table:
            print(f"no declared bands reach table {args.table!r}")
            return 1

    env = {
        k: _env(k, d)
        for k, d in (
            ("MYSQL_HOST", "127.0.0.1"),
            ("MYSQL_PORT", "3306"),
            ("MYSQL_USER", "root"),
            ("MYSQL_PASSWORD", ""),
            ("MYSQL_DATABASE", "sensordb"),
        )
    }
    conn = pymysql.connect(
        host="127.0.0.1",
        port=int(env["MYSQL_PORT"]),
        user=env["MYSQL_USER"],
        password=env["MYSQL_PASSWORD"],
        database=env["MYSQL_DATABASE"],
        # Rows are stamped naive UTC; a session on the server's own zone reads NOW()
        # an hour off and silently misses the newest hour (BUG-403).
        init_command=UTC_SESSION_INIT,
    )
    cur = conn.cursor()

    grand_bad = 0
    ambiguous: List[str] = []
    for table, sensors in sorted(by_table.items()):
        # Grouped by band for the SUMMARY line, but every decision below is per stream.
        #
        # The threshold started life on the group and that was wrong in a way the numbers
        # hid: iaq_data's six CO2 sensors came out 72.8% out of band, below the 95%
        # threshold, so nothing was touched. Per sensor, four of them were 96.9% -- a
        # clean unit error -- and two were 39.5%, a stream that was wrong and later
        # corrected. One average, two entirely different situations, and the group figure
        # described neither. A unit error belongs to an instrument, not to a quantity.
        groups: Dict[tuple, List[str]] = defaultdict(list)
        for uuid, (kind, lo, hi, unit) in sensors.items():
            groups[(kind, lo, hi, unit)].append(uuid)

        print(f"\n{table}  (declared {nature.get(table, 'unknown')})")
        for (kind, lo, hi, unit), uuids in sorted(groups.items()):
            per: Dict[str, Tuple[int, int]] = {}
            for uuid in uuids:
                cur.execute(
                    f"SELECT COUNT(*), SUM(value < %s OR value > %s) FROM `{table}` "  # nosec B608
                    f"WHERE uuid = %s",
                    (lo, hi, uuid),
                )
                total_u, bad_u = cur.fetchone()
                per[uuid] = (int(total_u or 0), int(bad_u or 0))

            total = sum(v[0] for v in per.values())
            bad = sum(v[1] for v in per.values())
            if not bad:
                print(f"  {kind:<26} {len(uuids):>4} sensor(s)  {total:>9,} rows   all in band")
                continue
            grand_bad += bad
            share = 100.0 * bad / total if total else 0.0
            print(
                f"  {kind:<26} {len(uuids):>4} sensor(s)  {total:>9,} rows   "
                f"{bad:,} OUT OF BAND ({share:.1f}%)  band {lo:g}..{hi:g} {unit}"
            )

            scale_errors = [
                u for u, (tt, bb) in per.items() if tt and bb / tt >= args.min_share
            ]
            events = [
                u for u, (tt, bb) in per.items() if tt and 0 < bb / tt < args.min_share
            ]
            if scale_errors:
                print(
                    f"      {len(scale_errors)} stream(s) are almost entirely out of band "
                    f"-- a scale error, not events"
                )
            for u in events:
                tt, bb = per[u]
                pct = 100.0 * bb / tt
                # NAMED, not silently skipped. A stream that is half wrong is neither a
                # clean unit error nor a scatter of events: most often it was wrong until
                # someone fixed it, and the honest remedy is a time-bounded delete that
                # this script deliberately does not guess at.
                ambiguous.append(f"{table} {u[:8]} {kind} {pct:.1f}% out of band")

            if not args.apply:
                continue
            if nature.get(table) != "synthetic":
                # A real instrument reading out of band is a FAULT, and the row is the
                # evidence. Reported, never deleted.
                print(
                    f"      NOT deleted: {table} is declared "
                    f"'{nature.get(table, 'unknown')}', not synthetic."
                )
                continue
            if not scale_errors:
                print(
                    f"      NOT deleted: no single stream is above the "
                    f"{args.min_share:.0%} unit-error threshold, so these rows are events."
                )
                continue
            ph = ",".join(["%s"] * len(scale_errors))
            cur.execute(
                f"DELETE FROM `{table}` WHERE uuid IN ({ph}) "  # nosec B608
                f"AND (value < %s OR value > %s)",
                scale_errors + [lo, hi],
            )
            conn.commit()
            print(
                f"      deleted {cur.rowcount:,} row(s) from {len(scale_errors)} "
                f"scale-error stream(s)"
            )

    if ambiguous:
        print(
            "\nPARTLY out of band, and left alone. Each of these is either a stream that "
            "was wrong until a date, or genuine events. Deciding needs a time bound, which "
            "this script will not guess:"
        )
        for line in ambiguous[:20]:
            print(f"  {line}")
        if len(ambiguous) > 20:
            print(f"  ... and {len(ambiguous) - 20} more")

    if not grand_bad:
        print("\nevery stored reading is inside its declared physical band")
    elif not args.apply:
        print(
            f"\n{grand_bad:,} row(s) are outside their declared physical band. "
            f"Re-run with --apply to remove them from SYNTHETIC sources; readings from a "
            f"source declared real are reported and never modified."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
